package entities

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

type Media struct {
	ent.Schema
}

func (Media) Mixin() []ent.Mixin {
	return []ent.Mixin{
		BaseEntitySchema{},
	}
}

func (Media) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			NotEmpty().
			Comment("Original filename"),
		field.String("alternative_text").
			Optional().
			Nillable().
			Comment("Alternative text for accessibility").
			StructTag(`json:"alternativeText,omitempty"`),
		field.String("caption").
			Optional().
			Nillable().
			Comment("User-provided caption"),
		field.Int("width").
			Optional().
			Nillable().
			Comment("Pixel width"),
		field.Int("height").
			Optional().
			Nillable().
			Comment("Pixel height"),
		field.String("hash").
			Optional().
			Nillable().
			Comment("Content hash used in filenames"),
		field.String("ext").
			Optional().
			Nillable().
			Comment("File extension including dot"),
		field.String("mime").
			Optional().
			Nillable().
			Comment("MIME type"),
		field.Float("size").
			Optional().
			Nillable().
			Comment("File size in MB"),
		field.String("url").
			NotEmpty().
			Comment("Accessible URL or path"),
		field.String("preview_url").
			Optional().
			Nillable().
			Comment("Preview URL generated by provider").
			StructTag(`json:"previewUrl,omitempty"`),
		field.String("provider").
			Optional().
			Nillable().
			Comment("Storage provider key"),
		field.JSON("provider_metadata", map[string]any{}).
			Optional().
			Comment("Provider-specific metadata").
			StructTag(`json:"providerMetadata,omitempty"`),
		field.String("folder_path").
			Optional().
			Nillable().
			Comment("Folder path within provider").
			StructTag(`json:"folderPath,omitempty"`),
		field.String("locale").
			Optional().
			Nillable().
			Comment("Locale if i18n is enabled"),
		field.Bool("is_url_signed").
			Optional().
			Nillable().
			Comment("Whether generated URLs are signed").
			StructTag(`json:"isUrlSigned,omitempty"`),
	}
}

func (Media) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("hash"),
		index.Fields("folder_path"),
	}
}

func (Media) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("formats", MediaFormat.Type),
	}
}

type MediaFormat struct {
	ent.Schema
}

func (MediaFormat) Mixin() []ent.Mixin {
	return []ent.Mixin{
		BaseEntitySchema{},
	}
}

func (MediaFormat) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			NotEmpty().
			Comment("Format key such as thumbnail or small"),
		field.String("ext").
			Optional().
			Nillable().
			Comment("File extension including dot"),
		field.String("url").
			NotEmpty().
			Comment("Accessible URL or path"),
		field.String("hash").
			Optional().
			Nillable().
			Comment("Content hash used in filenames"),
		field.String("mime").
			Optional().
			Nillable().
			Comment("MIME type"),
		field.Float("size").
			Optional().
			Nillable().
			Comment("File size in MB"),
		field.Int64("size_in_bytes").
			Optional().
			Nillable().
			Comment("Exact file size in bytes").
			StructTag(`json:"sizeInBytes,omitempty"`),
		field.Int("width").
			Optional().
			Nillable().
			Comment("Pixel width"),
		field.Int("height").
			Optional().
			Nillable().
			Comment("Pixel height"),
		field.JSON("provider_metadata", map[string]any{}).
			Optional().
			Comment("Provider-specific metadata").
			StructTag(`json:"providerMetadata,omitempty"`),
		field.String("path").
			Optional().
			Nillable().
			Comment("Provider-specific path"),
		field.Bool("is_url_signed").
			Optional().
			Nillable().
			Comment("Whether generated URLs are signed").
			StructTag(`json:"isUrlSigned,omitempty"`),
		field.UUID("media_id", uuid.UUID{}).
			Comment("Parent media ID").
			StructTag(`json:"mediaId"`),
	}
}

func (MediaFormat) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("media", Media.Type).
			Ref("formats").
			Field("media_id").
			Unique().
			Required(),
	}
}

func (MediaFormat) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("media_id", "hash").Unique(),
		index.Fields("name"),
	}
}
