// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/leeforge/framework/ent/casbinpolicy"
)

// CasbinPolicy is the model entity for the CasbinPolicy schema.
type CasbinPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Policy type: p, g, p2, etc.
	Ptype string `json:"ptype,omitempty"`
	// Policy value 0
	V0 string `json:"v0,omitempty"`
	// Policy value 1
	V1 string `json:"v1,omitempty"`
	// Policy value 2
	V2 string `json:"v2,omitempty"`
	// Policy value 3
	V3 string `json:"v3,omitempty"`
	// Policy value 4
	V4 string `json:"v4,omitempty"`
	// Policy value 5
	V5           string `json:"v5,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CasbinPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case casbinpolicy.FieldID:
			values[i] = new(sql.NullInt64)
		case casbinpolicy.FieldPtype, casbinpolicy.FieldV0, casbinpolicy.FieldV1, casbinpolicy.FieldV2, casbinpolicy.FieldV3, casbinpolicy.FieldV4, casbinpolicy.FieldV5:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CasbinPolicy fields.
func (_m *CasbinPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case casbinpolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case casbinpolicy.FieldPtype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ptype", values[i])
			} else if value.Valid {
				_m.Ptype = value.String
			}
		case casbinpolicy.FieldV0:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field v0", values[i])
			} else if value.Valid {
				_m.V0 = value.String
			}
		case casbinpolicy.FieldV1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field v1", values[i])
			} else if value.Valid {
				_m.V1 = value.String
			}
		case casbinpolicy.FieldV2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field v2", values[i])
			} else if value.Valid {
				_m.V2 = value.String
			}
		case casbinpolicy.FieldV3:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field v3", values[i])
			} else if value.Valid {
				_m.V3 = value.String
			}
		case casbinpolicy.FieldV4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field v4", values[i])
			} else if value.Valid {
				_m.V4 = value.String
			}
		case casbinpolicy.FieldV5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field v5", values[i])
			} else if value.Valid {
				_m.V5 = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CasbinPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *CasbinPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CasbinPolicy.
// Note that you need to call CasbinPolicy.Unwrap() before calling this method if this CasbinPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CasbinPolicy) Update() *CasbinPolicyUpdateOne {
	return NewCasbinPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CasbinPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CasbinPolicy) Unwrap() *CasbinPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CasbinPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CasbinPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("CasbinPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ptype=")
	builder.WriteString(_m.Ptype)
	builder.WriteString(", ")
	builder.WriteString("v0=")
	builder.WriteString(_m.V0)
	builder.WriteString(", ")
	builder.WriteString("v1=")
	builder.WriteString(_m.V1)
	builder.WriteString(", ")
	builder.WriteString("v2=")
	builder.WriteString(_m.V2)
	builder.WriteString(", ")
	builder.WriteString("v3=")
	builder.WriteString(_m.V3)
	builder.WriteString(", ")
	builder.WriteString("v4=")
	builder.WriteString(_m.V4)
	builder.WriteString(", ")
	builder.WriteString("v5=")
	builder.WriteString(_m.V5)
	builder.WriteByte(')')
	return builder.String()
}

// CasbinPolicies is a parsable slice of CasbinPolicy.
type CasbinPolicies []*CasbinPolicy
