// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/leeforge/framework/ent/casbinpolicy"
	"github.com/leeforge/framework/ent/predicate"
)

// CasbinPolicyDelete is the builder for deleting a CasbinPolicy entity.
type CasbinPolicyDelete struct {
	config
	hooks    []Hook
	mutation *CasbinPolicyMutation
}

// Where appends a list predicates to the CasbinPolicyDelete builder.
func (_d *CasbinPolicyDelete) Where(ps ...predicate.CasbinPolicy) *CasbinPolicyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CasbinPolicyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CasbinPolicyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CasbinPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(casbinpolicy.Table, sqlgraph.NewFieldSpec(casbinpolicy.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CasbinPolicyDeleteOne is the builder for deleting a single CasbinPolicy entity.
type CasbinPolicyDeleteOne struct {
	_d *CasbinPolicyDelete
}

// Where appends a list predicates to the CasbinPolicyDelete builder.
func (_d *CasbinPolicyDeleteOne) Where(ps ...predicate.CasbinPolicy) *CasbinPolicyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CasbinPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{casbinpolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CasbinPolicyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
