// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/leeforge/framework/ent/casbinpolicy"
)

// CasbinPolicyCreate is the builder for creating a CasbinPolicy entity.
type CasbinPolicyCreate struct {
	config
	mutation *CasbinPolicyMutation
	hooks    []Hook
}

// SetPtype sets the "ptype" field.
func (_c *CasbinPolicyCreate) SetPtype(v string) *CasbinPolicyCreate {
	_c.mutation.SetPtype(v)
	return _c
}

// SetV0 sets the "v0" field.
func (_c *CasbinPolicyCreate) SetV0(v string) *CasbinPolicyCreate {
	_c.mutation.SetV0(v)
	return _c
}

// SetNillableV0 sets the "v0" field if the given value is not nil.
func (_c *CasbinPolicyCreate) SetNillableV0(v *string) *CasbinPolicyCreate {
	if v != nil {
		_c.SetV0(*v)
	}
	return _c
}

// SetV1 sets the "v1" field.
func (_c *CasbinPolicyCreate) SetV1(v string) *CasbinPolicyCreate {
	_c.mutation.SetV1(v)
	return _c
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_c *CasbinPolicyCreate) SetNillableV1(v *string) *CasbinPolicyCreate {
	if v != nil {
		_c.SetV1(*v)
	}
	return _c
}

// SetV2 sets the "v2" field.
func (_c *CasbinPolicyCreate) SetV2(v string) *CasbinPolicyCreate {
	_c.mutation.SetV2(v)
	return _c
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_c *CasbinPolicyCreate) SetNillableV2(v *string) *CasbinPolicyCreate {
	if v != nil {
		_c.SetV2(*v)
	}
	return _c
}

// SetV3 sets the "v3" field.
func (_c *CasbinPolicyCreate) SetV3(v string) *CasbinPolicyCreate {
	_c.mutation.SetV3(v)
	return _c
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_c *CasbinPolicyCreate) SetNillableV3(v *string) *CasbinPolicyCreate {
	if v != nil {
		_c.SetV3(*v)
	}
	return _c
}

// SetV4 sets the "v4" field.
func (_c *CasbinPolicyCreate) SetV4(v string) *CasbinPolicyCreate {
	_c.mutation.SetV4(v)
	return _c
}

// SetNillableV4 sets the "v4" field if the given value is not nil.
func (_c *CasbinPolicyCreate) SetNillableV4(v *string) *CasbinPolicyCreate {
	if v != nil {
		_c.SetV4(*v)
	}
	return _c
}

// SetV5 sets the "v5" field.
func (_c *CasbinPolicyCreate) SetV5(v string) *CasbinPolicyCreate {
	_c.mutation.SetV5(v)
	return _c
}

// SetNillableV5 sets the "v5" field if the given value is not nil.
func (_c *CasbinPolicyCreate) SetNillableV5(v *string) *CasbinPolicyCreate {
	if v != nil {
		_c.SetV5(*v)
	}
	return _c
}

// Mutation returns the CasbinPolicyMutation object of the builder.
func (_c *CasbinPolicyCreate) Mutation() *CasbinPolicyMutation {
	return _c.mutation
}

// Save creates the CasbinPolicy in the database.
func (_c *CasbinPolicyCreate) Save(ctx context.Context) (*CasbinPolicy, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CasbinPolicyCreate) SaveX(ctx context.Context) *CasbinPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CasbinPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CasbinPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CasbinPolicyCreate) check() error {
	if _, ok := _c.mutation.Ptype(); !ok {
		return &ValidationError{Name: "ptype", err: errors.New(`ent: missing required field "CasbinPolicy.ptype"`)}
	}
	if v, ok := _c.mutation.Ptype(); ok {
		if err := casbinpolicy.PtypeValidator(v); err != nil {
			return &ValidationError{Name: "ptype", err: fmt.Errorf(`ent: validator failed for field "CasbinPolicy.ptype": %w`, err)}
		}
	}
	return nil
}

func (_c *CasbinPolicyCreate) sqlSave(ctx context.Context) (*CasbinPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CasbinPolicyCreate) createSpec() (*CasbinPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &CasbinPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(casbinpolicy.Table, sqlgraph.NewFieldSpec(casbinpolicy.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Ptype(); ok {
		_spec.SetField(casbinpolicy.FieldPtype, field.TypeString, value)
		_node.Ptype = value
	}
	if value, ok := _c.mutation.V0(); ok {
		_spec.SetField(casbinpolicy.FieldV0, field.TypeString, value)
		_node.V0 = value
	}
	if value, ok := _c.mutation.V1(); ok {
		_spec.SetField(casbinpolicy.FieldV1, field.TypeString, value)
		_node.V1 = value
	}
	if value, ok := _c.mutation.V2(); ok {
		_spec.SetField(casbinpolicy.FieldV2, field.TypeString, value)
		_node.V2 = value
	}
	if value, ok := _c.mutation.V3(); ok {
		_spec.SetField(casbinpolicy.FieldV3, field.TypeString, value)
		_node.V3 = value
	}
	if value, ok := _c.mutation.V4(); ok {
		_spec.SetField(casbinpolicy.FieldV4, field.TypeString, value)
		_node.V4 = value
	}
	if value, ok := _c.mutation.V5(); ok {
		_spec.SetField(casbinpolicy.FieldV5, field.TypeString, value)
		_node.V5 = value
	}
	return _node, _spec
}

// CasbinPolicyCreateBulk is the builder for creating many CasbinPolicy entities in bulk.
type CasbinPolicyCreateBulk struct {
	config
	err      error
	builders []*CasbinPolicyCreate
}

// Save creates the CasbinPolicy entities in the database.
func (_c *CasbinPolicyCreateBulk) Save(ctx context.Context) ([]*CasbinPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CasbinPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CasbinPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CasbinPolicyCreateBulk) SaveX(ctx context.Context) []*CasbinPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CasbinPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CasbinPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
