// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/leeforge/framework/ent/casbinpolicy"
	"github.com/leeforge/framework/ent/predicate"
)

// CasbinPolicyUpdate is the builder for updating CasbinPolicy entities.
type CasbinPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *CasbinPolicyMutation
}

// Where appends a list predicates to the CasbinPolicyUpdate builder.
func (_u *CasbinPolicyUpdate) Where(ps ...predicate.CasbinPolicy) *CasbinPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPtype sets the "ptype" field.
func (_u *CasbinPolicyUpdate) SetPtype(v string) *CasbinPolicyUpdate {
	_u.mutation.SetPtype(v)
	return _u
}

// SetNillablePtype sets the "ptype" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillablePtype(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetPtype(*v)
	}
	return _u
}

// SetV0 sets the "v0" field.
func (_u *CasbinPolicyUpdate) SetV0(v string) *CasbinPolicyUpdate {
	_u.mutation.SetV0(v)
	return _u
}

// SetNillableV0 sets the "v0" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillableV0(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetV0(*v)
	}
	return _u
}

// ClearV0 clears the value of the "v0" field.
func (_u *CasbinPolicyUpdate) ClearV0() *CasbinPolicyUpdate {
	_u.mutation.ClearV0()
	return _u
}

// SetV1 sets the "v1" field.
func (_u *CasbinPolicyUpdate) SetV1(v string) *CasbinPolicyUpdate {
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillableV1(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// ClearV1 clears the value of the "v1" field.
func (_u *CasbinPolicyUpdate) ClearV1() *CasbinPolicyUpdate {
	_u.mutation.ClearV1()
	return _u
}

// SetV2 sets the "v2" field.
func (_u *CasbinPolicyUpdate) SetV2(v string) *CasbinPolicyUpdate {
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillableV2(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// ClearV2 clears the value of the "v2" field.
func (_u *CasbinPolicyUpdate) ClearV2() *CasbinPolicyUpdate {
	_u.mutation.ClearV2()
	return _u
}

// SetV3 sets the "v3" field.
func (_u *CasbinPolicyUpdate) SetV3(v string) *CasbinPolicyUpdate {
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillableV3(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// ClearV3 clears the value of the "v3" field.
func (_u *CasbinPolicyUpdate) ClearV3() *CasbinPolicyUpdate {
	_u.mutation.ClearV3()
	return _u
}

// SetV4 sets the "v4" field.
func (_u *CasbinPolicyUpdate) SetV4(v string) *CasbinPolicyUpdate {
	_u.mutation.SetV4(v)
	return _u
}

// SetNillableV4 sets the "v4" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillableV4(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetV4(*v)
	}
	return _u
}

// ClearV4 clears the value of the "v4" field.
func (_u *CasbinPolicyUpdate) ClearV4() *CasbinPolicyUpdate {
	_u.mutation.ClearV4()
	return _u
}

// SetV5 sets the "v5" field.
func (_u *CasbinPolicyUpdate) SetV5(v string) *CasbinPolicyUpdate {
	_u.mutation.SetV5(v)
	return _u
}

// SetNillableV5 sets the "v5" field if the given value is not nil.
func (_u *CasbinPolicyUpdate) SetNillableV5(v *string) *CasbinPolicyUpdate {
	if v != nil {
		_u.SetV5(*v)
	}
	return _u
}

// ClearV5 clears the value of the "v5" field.
func (_u *CasbinPolicyUpdate) ClearV5() *CasbinPolicyUpdate {
	_u.mutation.ClearV5()
	return _u
}

// Mutation returns the CasbinPolicyMutation object of the builder.
func (_u *CasbinPolicyUpdate) Mutation() *CasbinPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CasbinPolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CasbinPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CasbinPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CasbinPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CasbinPolicyUpdate) check() error {
	if v, ok := _u.mutation.Ptype(); ok {
		if err := casbinpolicy.PtypeValidator(v); err != nil {
			return &ValidationError{Name: "ptype", err: fmt.Errorf(`ent: validator failed for field "CasbinPolicy.ptype": %w`, err)}
		}
	}
	return nil
}

func (_u *CasbinPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(casbinpolicy.Table, casbinpolicy.Columns, sqlgraph.NewFieldSpec(casbinpolicy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ptype(); ok {
		_spec.SetField(casbinpolicy.FieldPtype, field.TypeString, value)
	}
	if value, ok := _u.mutation.V0(); ok {
		_spec.SetField(casbinpolicy.FieldV0, field.TypeString, value)
	}
	if _u.mutation.V0Cleared() {
		_spec.ClearField(casbinpolicy.FieldV0, field.TypeString)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(casbinpolicy.FieldV1, field.TypeString, value)
	}
	if _u.mutation.V1Cleared() {
		_spec.ClearField(casbinpolicy.FieldV1, field.TypeString)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(casbinpolicy.FieldV2, field.TypeString, value)
	}
	if _u.mutation.V2Cleared() {
		_spec.ClearField(casbinpolicy.FieldV2, field.TypeString)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(casbinpolicy.FieldV3, field.TypeString, value)
	}
	if _u.mutation.V3Cleared() {
		_spec.ClearField(casbinpolicy.FieldV3, field.TypeString)
	}
	if value, ok := _u.mutation.V4(); ok {
		_spec.SetField(casbinpolicy.FieldV4, field.TypeString, value)
	}
	if _u.mutation.V4Cleared() {
		_spec.ClearField(casbinpolicy.FieldV4, field.TypeString)
	}
	if value, ok := _u.mutation.V5(); ok {
		_spec.SetField(casbinpolicy.FieldV5, field.TypeString, value)
	}
	if _u.mutation.V5Cleared() {
		_spec.ClearField(casbinpolicy.FieldV5, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{casbinpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CasbinPolicyUpdateOne is the builder for updating a single CasbinPolicy entity.
type CasbinPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CasbinPolicyMutation
}

// SetPtype sets the "ptype" field.
func (_u *CasbinPolicyUpdateOne) SetPtype(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetPtype(v)
	return _u
}

// SetNillablePtype sets the "ptype" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillablePtype(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetPtype(*v)
	}
	return _u
}

// SetV0 sets the "v0" field.
func (_u *CasbinPolicyUpdateOne) SetV0(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetV0(v)
	return _u
}

// SetNillableV0 sets the "v0" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillableV0(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetV0(*v)
	}
	return _u
}

// ClearV0 clears the value of the "v0" field.
func (_u *CasbinPolicyUpdateOne) ClearV0() *CasbinPolicyUpdateOne {
	_u.mutation.ClearV0()
	return _u
}

// SetV1 sets the "v1" field.
func (_u *CasbinPolicyUpdateOne) SetV1(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillableV1(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// ClearV1 clears the value of the "v1" field.
func (_u *CasbinPolicyUpdateOne) ClearV1() *CasbinPolicyUpdateOne {
	_u.mutation.ClearV1()
	return _u
}

// SetV2 sets the "v2" field.
func (_u *CasbinPolicyUpdateOne) SetV2(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillableV2(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// ClearV2 clears the value of the "v2" field.
func (_u *CasbinPolicyUpdateOne) ClearV2() *CasbinPolicyUpdateOne {
	_u.mutation.ClearV2()
	return _u
}

// SetV3 sets the "v3" field.
func (_u *CasbinPolicyUpdateOne) SetV3(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillableV3(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// ClearV3 clears the value of the "v3" field.
func (_u *CasbinPolicyUpdateOne) ClearV3() *CasbinPolicyUpdateOne {
	_u.mutation.ClearV3()
	return _u
}

// SetV4 sets the "v4" field.
func (_u *CasbinPolicyUpdateOne) SetV4(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetV4(v)
	return _u
}

// SetNillableV4 sets the "v4" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillableV4(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetV4(*v)
	}
	return _u
}

// ClearV4 clears the value of the "v4" field.
func (_u *CasbinPolicyUpdateOne) ClearV4() *CasbinPolicyUpdateOne {
	_u.mutation.ClearV4()
	return _u
}

// SetV5 sets the "v5" field.
func (_u *CasbinPolicyUpdateOne) SetV5(v string) *CasbinPolicyUpdateOne {
	_u.mutation.SetV5(v)
	return _u
}

// SetNillableV5 sets the "v5" field if the given value is not nil.
func (_u *CasbinPolicyUpdateOne) SetNillableV5(v *string) *CasbinPolicyUpdateOne {
	if v != nil {
		_u.SetV5(*v)
	}
	return _u
}

// ClearV5 clears the value of the "v5" field.
func (_u *CasbinPolicyUpdateOne) ClearV5() *CasbinPolicyUpdateOne {
	_u.mutation.ClearV5()
	return _u
}

// Mutation returns the CasbinPolicyMutation object of the builder.
func (_u *CasbinPolicyUpdateOne) Mutation() *CasbinPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the CasbinPolicyUpdate builder.
func (_u *CasbinPolicyUpdateOne) Where(ps ...predicate.CasbinPolicy) *CasbinPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CasbinPolicyUpdateOne) Select(field string, fields ...string) *CasbinPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CasbinPolicy entity.
func (_u *CasbinPolicyUpdateOne) Save(ctx context.Context) (*CasbinPolicy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CasbinPolicyUpdateOne) SaveX(ctx context.Context) *CasbinPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CasbinPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CasbinPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CasbinPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Ptype(); ok {
		if err := casbinpolicy.PtypeValidator(v); err != nil {
			return &ValidationError{Name: "ptype", err: fmt.Errorf(`ent: validator failed for field "CasbinPolicy.ptype": %w`, err)}
		}
	}
	return nil
}

func (_u *CasbinPolicyUpdateOne) sqlSave(ctx context.Context) (_node *CasbinPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(casbinpolicy.Table, casbinpolicy.Columns, sqlgraph.NewFieldSpec(casbinpolicy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CasbinPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, casbinpolicy.FieldID)
		for _, f := range fields {
			if !casbinpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != casbinpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ptype(); ok {
		_spec.SetField(casbinpolicy.FieldPtype, field.TypeString, value)
	}
	if value, ok := _u.mutation.V0(); ok {
		_spec.SetField(casbinpolicy.FieldV0, field.TypeString, value)
	}
	if _u.mutation.V0Cleared() {
		_spec.ClearField(casbinpolicy.FieldV0, field.TypeString)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(casbinpolicy.FieldV1, field.TypeString, value)
	}
	if _u.mutation.V1Cleared() {
		_spec.ClearField(casbinpolicy.FieldV1, field.TypeString)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(casbinpolicy.FieldV2, field.TypeString, value)
	}
	if _u.mutation.V2Cleared() {
		_spec.ClearField(casbinpolicy.FieldV2, field.TypeString)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(casbinpolicy.FieldV3, field.TypeString, value)
	}
	if _u.mutation.V3Cleared() {
		_spec.ClearField(casbinpolicy.FieldV3, field.TypeString)
	}
	if value, ok := _u.mutation.V4(); ok {
		_spec.SetField(casbinpolicy.FieldV4, field.TypeString, value)
	}
	if _u.mutation.V4Cleared() {
		_spec.ClearField(casbinpolicy.FieldV4, field.TypeString)
	}
	if value, ok := _u.mutation.V5(); ok {
		_spec.SetField(casbinpolicy.FieldV5, field.TypeString, value)
	}
	if _u.mutation.V5Cleared() {
		_spec.ClearField(casbinpolicy.FieldV5, field.TypeString)
	}
	_node = &CasbinPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{casbinpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
