// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/leeforge/framework/ent/casbinpolicy"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CasbinPolicy is the client for interacting with the CasbinPolicy builders.
	CasbinPolicy *CasbinPolicyClient
	// Media is the client for interacting with the Media builders.
	Media *MediaClient
	// MediaFormat is the client for interacting with the MediaFormat builders.
	MediaFormat *MediaFormatClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CasbinPolicy = NewCasbinPolicyClient(c.config)
	c.Media = NewMediaClient(c.config)
	c.MediaFormat = NewMediaFormatClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		CasbinPolicy: NewCasbinPolicyClient(cfg),
		Media:        NewMediaClient(cfg),
		MediaFormat:  NewMediaFormatClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		CasbinPolicy: NewCasbinPolicyClient(cfg),
		Media:        NewMediaClient(cfg),
		MediaFormat:  NewMediaFormatClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CasbinPolicy.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CasbinPolicy.Use(hooks...)
	c.Media.Use(hooks...)
	c.MediaFormat.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.CasbinPolicy.Intercept(interceptors...)
	c.Media.Intercept(interceptors...)
	c.MediaFormat.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CasbinPolicyMutation:
		return c.CasbinPolicy.mutate(ctx, m)
	case *MediaMutation:
		return c.Media.mutate(ctx, m)
	case *MediaFormatMutation:
		return c.MediaFormat.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CasbinPolicyClient is a client for the CasbinPolicy schema.
type CasbinPolicyClient struct {
	config
}

// NewCasbinPolicyClient returns a client for the CasbinPolicy from the given config.
func NewCasbinPolicyClient(c config) *CasbinPolicyClient {
	return &CasbinPolicyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `casbinpolicy.Hooks(f(g(h())))`.
func (c *CasbinPolicyClient) Use(hooks ...Hook) {
	c.hooks.CasbinPolicy = append(c.hooks.CasbinPolicy, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `casbinpolicy.Intercept(f(g(h())))`.
func (c *CasbinPolicyClient) Intercept(interceptors ...Interceptor) {
	c.inters.CasbinPolicy = append(c.inters.CasbinPolicy, interceptors...)
}

// Create returns a builder for creating a CasbinPolicy entity.
func (c *CasbinPolicyClient) Create() *CasbinPolicyCreate {
	mutation := newCasbinPolicyMutation(c.config, OpCreate)
	return &CasbinPolicyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CasbinPolicy entities.
func (c *CasbinPolicyClient) CreateBulk(builders ...*CasbinPolicyCreate) *CasbinPolicyCreateBulk {
	return &CasbinPolicyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CasbinPolicyClient) MapCreateBulk(slice any, setFunc func(*CasbinPolicyCreate, int)) *CasbinPolicyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CasbinPolicyCreateBulk{err: fmt.Errorf("calling to CasbinPolicyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CasbinPolicyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CasbinPolicyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CasbinPolicy.
func (c *CasbinPolicyClient) Update() *CasbinPolicyUpdate {
	mutation := newCasbinPolicyMutation(c.config, OpUpdate)
	return &CasbinPolicyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CasbinPolicyClient) UpdateOne(_m *CasbinPolicy) *CasbinPolicyUpdateOne {
	mutation := newCasbinPolicyMutation(c.config, OpUpdateOne, withCasbinPolicy(_m))
	return &CasbinPolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CasbinPolicyClient) UpdateOneID(id int) *CasbinPolicyUpdateOne {
	mutation := newCasbinPolicyMutation(c.config, OpUpdateOne, withCasbinPolicyID(id))
	return &CasbinPolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CasbinPolicy.
func (c *CasbinPolicyClient) Delete() *CasbinPolicyDelete {
	mutation := newCasbinPolicyMutation(c.config, OpDelete)
	return &CasbinPolicyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CasbinPolicyClient) DeleteOne(_m *CasbinPolicy) *CasbinPolicyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CasbinPolicyClient) DeleteOneID(id int) *CasbinPolicyDeleteOne {
	builder := c.Delete().Where(casbinpolicy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CasbinPolicyDeleteOne{builder}
}

// Query returns a query builder for CasbinPolicy.
func (c *CasbinPolicyClient) Query() *CasbinPolicyQuery {
	return &CasbinPolicyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCasbinPolicy},
		inters: c.Interceptors(),
	}
}

// Get returns a CasbinPolicy entity by its id.
func (c *CasbinPolicyClient) Get(ctx context.Context, id int) (*CasbinPolicy, error) {
	return c.Query().Where(casbinpolicy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CasbinPolicyClient) GetX(ctx context.Context, id int) *CasbinPolicy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CasbinPolicyClient) Hooks() []Hook {
	return c.hooks.CasbinPolicy
}

// Interceptors returns the client interceptors.
func (c *CasbinPolicyClient) Interceptors() []Interceptor {
	return c.inters.CasbinPolicy
}

func (c *CasbinPolicyClient) mutate(ctx context.Context, m *CasbinPolicyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CasbinPolicyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CasbinPolicyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CasbinPolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CasbinPolicyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CasbinPolicy mutation op: %q", m.Op())
	}
}

// MediaClient is a client for the Media schema.
type MediaClient struct {
	config
}

// NewMediaClient returns a client for the Media from the given config.
func NewMediaClient(c config) *MediaClient {
	return &MediaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `media.Hooks(f(g(h())))`.
func (c *MediaClient) Use(hooks ...Hook) {
	c.hooks.Media = append(c.hooks.Media, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `media.Intercept(f(g(h())))`.
func (c *MediaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Media = append(c.inters.Media, interceptors...)
}

// Create returns a builder for creating a Media entity.
func (c *MediaClient) Create() *MediaCreate {
	mutation := newMediaMutation(c.config, OpCreate)
	return &MediaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Media entities.
func (c *MediaClient) CreateBulk(builders ...*MediaCreate) *MediaCreateBulk {
	return &MediaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MediaClient) MapCreateBulk(slice any, setFunc func(*MediaCreate, int)) *MediaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MediaCreateBulk{err: fmt.Errorf("calling to MediaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MediaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MediaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Media.
func (c *MediaClient) Update() *MediaUpdate {
	mutation := newMediaMutation(c.config, OpUpdate)
	return &MediaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MediaClient) UpdateOne(_m *Media) *MediaUpdateOne {
	mutation := newMediaMutation(c.config, OpUpdateOne, withMedia(_m))
	return &MediaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MediaClient) UpdateOneID(id uuid.UUID) *MediaUpdateOne {
	mutation := newMediaMutation(c.config, OpUpdateOne, withMediaID(id))
	return &MediaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Media.
func (c *MediaClient) Delete() *MediaDelete {
	mutation := newMediaMutation(c.config, OpDelete)
	return &MediaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MediaClient) DeleteOne(_m *Media) *MediaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MediaClient) DeleteOneID(id uuid.UUID) *MediaDeleteOne {
	builder := c.Delete().Where(media.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MediaDeleteOne{builder}
}

// Query returns a query builder for Media.
func (c *MediaClient) Query() *MediaQuery {
	return &MediaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMedia},
		inters: c.Interceptors(),
	}
}

// Get returns a Media entity by its id.
func (c *MediaClient) Get(ctx context.Context, id uuid.UUID) (*Media, error) {
	return c.Query().Where(media.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MediaClient) GetX(ctx context.Context, id uuid.UUID) *Media {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFormats queries the formats edge of a Media.
func (c *MediaClient) QueryFormats(_m *Media) *MediaFormatQuery {
	query := (&MediaFormatClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(media.Table, media.FieldID, id),
			sqlgraph.To(mediaformat.Table, mediaformat.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, media.FormatsTable, media.FormatsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MediaClient) Hooks() []Hook {
	return c.hooks.Media
}

// Interceptors returns the client interceptors.
func (c *MediaClient) Interceptors() []Interceptor {
	return c.inters.Media
}

func (c *MediaClient) mutate(ctx context.Context, m *MediaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MediaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MediaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MediaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MediaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Media mutation op: %q", m.Op())
	}
}

// MediaFormatClient is a client for the MediaFormat schema.
type MediaFormatClient struct {
	config
}

// NewMediaFormatClient returns a client for the MediaFormat from the given config.
func NewMediaFormatClient(c config) *MediaFormatClient {
	return &MediaFormatClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mediaformat.Hooks(f(g(h())))`.
func (c *MediaFormatClient) Use(hooks ...Hook) {
	c.hooks.MediaFormat = append(c.hooks.MediaFormat, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mediaformat.Intercept(f(g(h())))`.
func (c *MediaFormatClient) Intercept(interceptors ...Interceptor) {
	c.inters.MediaFormat = append(c.inters.MediaFormat, interceptors...)
}

// Create returns a builder for creating a MediaFormat entity.
func (c *MediaFormatClient) Create() *MediaFormatCreate {
	mutation := newMediaFormatMutation(c.config, OpCreate)
	return &MediaFormatCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MediaFormat entities.
func (c *MediaFormatClient) CreateBulk(builders ...*MediaFormatCreate) *MediaFormatCreateBulk {
	return &MediaFormatCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MediaFormatClient) MapCreateBulk(slice any, setFunc func(*MediaFormatCreate, int)) *MediaFormatCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MediaFormatCreateBulk{err: fmt.Errorf("calling to MediaFormatClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MediaFormatCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MediaFormatCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MediaFormat.
func (c *MediaFormatClient) Update() *MediaFormatUpdate {
	mutation := newMediaFormatMutation(c.config, OpUpdate)
	return &MediaFormatUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MediaFormatClient) UpdateOne(_m *MediaFormat) *MediaFormatUpdateOne {
	mutation := newMediaFormatMutation(c.config, OpUpdateOne, withMediaFormat(_m))
	return &MediaFormatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MediaFormatClient) UpdateOneID(id uuid.UUID) *MediaFormatUpdateOne {
	mutation := newMediaFormatMutation(c.config, OpUpdateOne, withMediaFormatID(id))
	return &MediaFormatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MediaFormat.
func (c *MediaFormatClient) Delete() *MediaFormatDelete {
	mutation := newMediaFormatMutation(c.config, OpDelete)
	return &MediaFormatDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MediaFormatClient) DeleteOne(_m *MediaFormat) *MediaFormatDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MediaFormatClient) DeleteOneID(id uuid.UUID) *MediaFormatDeleteOne {
	builder := c.Delete().Where(mediaformat.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MediaFormatDeleteOne{builder}
}

// Query returns a query builder for MediaFormat.
func (c *MediaFormatClient) Query() *MediaFormatQuery {
	return &MediaFormatQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMediaFormat},
		inters: c.Interceptors(),
	}
}

// Get returns a MediaFormat entity by its id.
func (c *MediaFormatClient) Get(ctx context.Context, id uuid.UUID) (*MediaFormat, error) {
	return c.Query().Where(mediaformat.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MediaFormatClient) GetX(ctx context.Context, id uuid.UUID) *MediaFormat {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMedia queries the media edge of a MediaFormat.
func (c *MediaFormatClient) QueryMedia(_m *MediaFormat) *MediaQuery {
	query := (&MediaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaformat.Table, mediaformat.FieldID, id),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaformat.MediaTable, mediaformat.MediaColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MediaFormatClient) Hooks() []Hook {
	return c.hooks.MediaFormat
}

// Interceptors returns the client interceptors.
func (c *MediaFormatClient) Interceptors() []Interceptor {
	return c.inters.MediaFormat
}

func (c *MediaFormatClient) mutate(ctx context.Context, m *MediaFormatMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MediaFormatCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MediaFormatUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MediaFormatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MediaFormatDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MediaFormat mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CasbinPolicy, Media, MediaFormat []ent.Hook
	}
	inters struct {
		CasbinPolicy, Media, MediaFormat []ent.Interceptor
	}
)
