// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
)

// Media is the model entity for the Media schema.
type Media struct {
	config `json:"-"`
	// ID of the ent.
	// 唯一标识
	ID uuid.UUID `json:"id,omitempty"`
	// 租户ID
	TenantID string `json:"tenant_id,omitempty"`
	// 创建者ID
	CreatedByID uuid.UUID `json:"created_by_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新者ID
	UpdatedByID uuid.UUID `json:"updated_by_id,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除者ID
	DeletedByID uuid.UUID `json:"deleted_by_id,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 发布时间
	PublishedAt time.Time `json:"published_at,omitempty"`
	// 归档时间
	ArchivedAt time.Time `json:"archived_at,omitempty"`
	// Original filename
	Name string `json:"name,omitempty"`
	// Alternative text for accessibility
	AlternativeText *string `json:"alternative_text,omitempty"`
	// User-provided caption
	Caption *string `json:"caption,omitempty"`
	// Pixel width
	Width *int `json:"width,omitempty"`
	// Pixel height
	Height *int `json:"height,omitempty"`
	// Content hash used in filenames
	Hash *string `json:"hash,omitempty"`
	// File extension including dot
	Ext *string `json:"ext,omitempty"`
	// MIME type
	Mime *string `json:"mime,omitempty"`
	// File size in MB
	Size *float64 `json:"size,omitempty"`
	// Accessible URL or path
	URL string `json:"url,omitempty"`
	// Preview URL generated by provider
	PreviewURL *string `json:"preview_url,omitempty"`
	// Storage provider key
	Provider *string `json:"provider,omitempty"`
	// Provider-specific metadata
	ProviderMetadata map[string]interface{} `json:"provider_metadata,omitempty"`
	// Folder path within provider
	FolderPath *string `json:"folder_path,omitempty"`
	// Locale if i18n is enabled
	Locale *string `json:"locale,omitempty"`
	// Whether generated URLs are signed
	IsURLSigned *bool `json:"is_url_signed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaQuery when eager-loading is set.
	Edges        MediaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaEdges holds the relations/edges for other nodes in the graph.
type MediaEdges struct {
	// Formats holds the value of the formats edge.
	Formats []*MediaFormat `json:"formats,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FormatsOrErr returns the Formats value or an error if the edge
// was not loaded in eager-loading.
func (e MediaEdges) FormatsOrErr() ([]*MediaFormat, error) {
	if e.loadedTypes[0] {
		return e.Formats, nil
	}
	return nil, &NotLoadedError{edge: "formats"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Media) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case media.FieldProviderMetadata:
			values[i] = new([]byte)
		case media.FieldIsURLSigned:
			values[i] = new(sql.NullBool)
		case media.FieldSize:
			values[i] = new(sql.NullFloat64)
		case media.FieldWidth, media.FieldHeight:
			values[i] = new(sql.NullInt64)
		case media.FieldTenantID, media.FieldName, media.FieldAlternativeText, media.FieldCaption, media.FieldHash, media.FieldExt, media.FieldMime, media.FieldURL, media.FieldPreviewURL, media.FieldProvider, media.FieldFolderPath, media.FieldLocale:
			values[i] = new(sql.NullString)
		case media.FieldCreatedAt, media.FieldUpdatedAt, media.FieldDeletedAt, media.FieldPublishedAt, media.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		case media.FieldID, media.FieldCreatedByID, media.FieldUpdatedByID, media.FieldDeletedByID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Media fields.
func (_m *Media) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case media.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case media.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case media.FieldCreatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value != nil {
				_m.CreatedByID = *value
			}
		case media.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case media.FieldUpdatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_id", values[i])
			} else if value != nil {
				_m.UpdatedByID = *value
			}
		case media.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case media.FieldDeletedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by_id", values[i])
			} else if value != nil {
				_m.DeletedByID = *value
			}
		case media.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case media.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		case media.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = value.Time
			}
		case media.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case media.FieldAlternativeText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alternative_text", values[i])
			} else if value.Valid {
				_m.AlternativeText = new(string)
				*_m.AlternativeText = value.String
			}
		case media.FieldCaption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caption", values[i])
			} else if value.Valid {
				_m.Caption = new(string)
				*_m.Caption = value.String
			}
		case media.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = new(int)
				*_m.Width = int(value.Int64)
			}
		case media.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = new(int)
				*_m.Height = int(value.Int64)
			}
		case media.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = new(string)
				*_m.Hash = value.String
			}
		case media.FieldExt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ext", values[i])
			} else if value.Valid {
				_m.Ext = new(string)
				*_m.Ext = value.String
			}
		case media.FieldMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime", values[i])
			} else if value.Valid {
				_m.Mime = new(string)
				*_m.Mime = value.String
			}
		case media.FieldSize:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = new(float64)
				*_m.Size = value.Float64
			}
		case media.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case media.FieldPreviewURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview_url", values[i])
			} else if value.Valid {
				_m.PreviewURL = new(string)
				*_m.PreviewURL = value.String
			}
		case media.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = new(string)
				*_m.Provider = value.String
			}
		case media.FieldProviderMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProviderMetadata); err != nil {
					return fmt.Errorf("unmarshal field provider_metadata: %w", err)
				}
			}
		case media.FieldFolderPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folder_path", values[i])
			} else if value.Valid {
				_m.FolderPath = new(string)
				*_m.FolderPath = value.String
			}
		case media.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = new(string)
				*_m.Locale = value.String
			}
		case media.FieldIsURLSigned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_url_signed", values[i])
			} else if value.Valid {
				_m.IsURLSigned = new(bool)
				*_m.IsURLSigned = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Media.
// This includes values selected through modifiers, order, etc.
func (_m *Media) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFormats queries the "formats" edge of the Media entity.
func (_m *Media) QueryFormats() *MediaFormatQuery {
	return NewMediaClient(_m.config).QueryFormats(_m)
}

// Update returns a builder for updating this Media.
// Note that you need to call Media.Unwrap() before calling this method if this Media
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Media) Update() *MediaUpdateOne {
	return NewMediaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Media entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Media) Unwrap() *Media {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Media is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Media) String() string {
	var builder strings.Builder
	builder.WriteString("Media(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("created_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedByID))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedByID))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("archived_at=")
	builder.WriteString(_m.ArchivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.AlternativeText; v != nil {
		builder.WriteString("alternative_text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Caption; v != nil {
		builder.WriteString("caption=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Height; v != nil {
		builder.WriteString("height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Hash; v != nil {
		builder.WriteString("hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Ext; v != nil {
		builder.WriteString("ext=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Mime; v != nil {
		builder.WriteString("mime=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Size; v != nil {
		builder.WriteString("size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.PreviewURL; v != nil {
		builder.WriteString("preview_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Provider; v != nil {
		builder.WriteString("provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("provider_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderMetadata))
	builder.WriteString(", ")
	if v := _m.FolderPath; v != nil {
		builder.WriteString("folder_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Locale; v != nil {
		builder.WriteString("locale=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IsURLSigned; v != nil {
		builder.WriteString("is_url_signed=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaSlice is a parsable slice of Media.
type MediaSlice []*Media
