// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
	"github.com/leeforge/framework/ent/predicate"
)

// MediaUpdate is the builder for updating Media entities.
type MediaUpdate struct {
	config
	hooks    []Hook
	mutation *MediaMutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (_u *MediaUpdate) Where(ps ...predicate.Media) *MediaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *MediaUpdate) SetTenantID(v string) *MediaUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableTenantID(v *string) *MediaUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *MediaUpdate) SetUpdatedByID(v uuid.UUID) *MediaUpdate {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableUpdatedByID(v *uuid.UUID) *MediaUpdate {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *MediaUpdate) ClearUpdatedByID() *MediaUpdate {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaUpdate) SetUpdatedAt(v time.Time) *MediaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MediaUpdate) ClearUpdatedAt() *MediaUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *MediaUpdate) SetDeletedByID(v uuid.UUID) *MediaUpdate {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableDeletedByID(v *uuid.UUID) *MediaUpdate {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *MediaUpdate) ClearDeletedByID() *MediaUpdate {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MediaUpdate) SetDeletedAt(v time.Time) *MediaUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableDeletedAt(v *time.Time) *MediaUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MediaUpdate) ClearDeletedAt() *MediaUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MediaUpdate) SetPublishedAt(v time.Time) *MediaUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MediaUpdate) SetNillablePublishedAt(v *time.Time) *MediaUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MediaUpdate) ClearPublishedAt() *MediaUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *MediaUpdate) SetArchivedAt(v time.Time) *MediaUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableArchivedAt(v *time.Time) *MediaUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *MediaUpdate) ClearArchivedAt() *MediaUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *MediaUpdate) SetName(v string) *MediaUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableName(v *string) *MediaUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAlternativeText sets the "alternative_text" field.
func (_u *MediaUpdate) SetAlternativeText(v string) *MediaUpdate {
	_u.mutation.SetAlternativeText(v)
	return _u
}

// SetNillableAlternativeText sets the "alternative_text" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableAlternativeText(v *string) *MediaUpdate {
	if v != nil {
		_u.SetAlternativeText(*v)
	}
	return _u
}

// ClearAlternativeText clears the value of the "alternative_text" field.
func (_u *MediaUpdate) ClearAlternativeText() *MediaUpdate {
	_u.mutation.ClearAlternativeText()
	return _u
}

// SetCaption sets the "caption" field.
func (_u *MediaUpdate) SetCaption(v string) *MediaUpdate {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableCaption(v *string) *MediaUpdate {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *MediaUpdate) ClearCaption() *MediaUpdate {
	_u.mutation.ClearCaption()
	return _u
}

// SetWidth sets the "width" field.
func (_u *MediaUpdate) SetWidth(v int) *MediaUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableWidth(v *int) *MediaUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *MediaUpdate) AddWidth(v int) *MediaUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *MediaUpdate) ClearWidth() *MediaUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *MediaUpdate) SetHeight(v int) *MediaUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableHeight(v *int) *MediaUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *MediaUpdate) AddHeight(v int) *MediaUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *MediaUpdate) ClearHeight() *MediaUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetHash sets the "hash" field.
func (_u *MediaUpdate) SetHash(v string) *MediaUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableHash(v *string) *MediaUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *MediaUpdate) ClearHash() *MediaUpdate {
	_u.mutation.ClearHash()
	return _u
}

// SetExt sets the "ext" field.
func (_u *MediaUpdate) SetExt(v string) *MediaUpdate {
	_u.mutation.SetExt(v)
	return _u
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableExt(v *string) *MediaUpdate {
	if v != nil {
		_u.SetExt(*v)
	}
	return _u
}

// ClearExt clears the value of the "ext" field.
func (_u *MediaUpdate) ClearExt() *MediaUpdate {
	_u.mutation.ClearExt()
	return _u
}

// SetMime sets the "mime" field.
func (_u *MediaUpdate) SetMime(v string) *MediaUpdate {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableMime(v *string) *MediaUpdate {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// ClearMime clears the value of the "mime" field.
func (_u *MediaUpdate) ClearMime() *MediaUpdate {
	_u.mutation.ClearMime()
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaUpdate) SetSize(v float64) *MediaUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableSize(v *float64) *MediaUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaUpdate) AddSize(v float64) *MediaUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *MediaUpdate) ClearSize() *MediaUpdate {
	_u.mutation.ClearSize()
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaUpdate) SetURL(v string) *MediaUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableURL(v *string) *MediaUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetPreviewURL sets the "preview_url" field.
func (_u *MediaUpdate) SetPreviewURL(v string) *MediaUpdate {
	_u.mutation.SetPreviewURL(v)
	return _u
}

// SetNillablePreviewURL sets the "preview_url" field if the given value is not nil.
func (_u *MediaUpdate) SetNillablePreviewURL(v *string) *MediaUpdate {
	if v != nil {
		_u.SetPreviewURL(*v)
	}
	return _u
}

// ClearPreviewURL clears the value of the "preview_url" field.
func (_u *MediaUpdate) ClearPreviewURL() *MediaUpdate {
	_u.mutation.ClearPreviewURL()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *MediaUpdate) SetProvider(v string) *MediaUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableProvider(v *string) *MediaUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *MediaUpdate) ClearProvider() *MediaUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetProviderMetadata sets the "provider_metadata" field.
func (_u *MediaUpdate) SetProviderMetadata(v map[string]interface{}) *MediaUpdate {
	_u.mutation.SetProviderMetadata(v)
	return _u
}

// ClearProviderMetadata clears the value of the "provider_metadata" field.
func (_u *MediaUpdate) ClearProviderMetadata() *MediaUpdate {
	_u.mutation.ClearProviderMetadata()
	return _u
}

// SetFolderPath sets the "folder_path" field.
func (_u *MediaUpdate) SetFolderPath(v string) *MediaUpdate {
	_u.mutation.SetFolderPath(v)
	return _u
}

// SetNillableFolderPath sets the "folder_path" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableFolderPath(v *string) *MediaUpdate {
	if v != nil {
		_u.SetFolderPath(*v)
	}
	return _u
}

// ClearFolderPath clears the value of the "folder_path" field.
func (_u *MediaUpdate) ClearFolderPath() *MediaUpdate {
	_u.mutation.ClearFolderPath()
	return _u
}

// SetLocale sets the "locale" field.
func (_u *MediaUpdate) SetLocale(v string) *MediaUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableLocale(v *string) *MediaUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// ClearLocale clears the value of the "locale" field.
func (_u *MediaUpdate) ClearLocale() *MediaUpdate {
	_u.mutation.ClearLocale()
	return _u
}

// SetIsURLSigned sets the "is_url_signed" field.
func (_u *MediaUpdate) SetIsURLSigned(v bool) *MediaUpdate {
	_u.mutation.SetIsURLSigned(v)
	return _u
}

// SetNillableIsURLSigned sets the "is_url_signed" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableIsURLSigned(v *bool) *MediaUpdate {
	if v != nil {
		_u.SetIsURLSigned(*v)
	}
	return _u
}

// ClearIsURLSigned clears the value of the "is_url_signed" field.
func (_u *MediaUpdate) ClearIsURLSigned() *MediaUpdate {
	_u.mutation.ClearIsURLSigned()
	return _u
}

// AddFormatIDs adds the "formats" edge to the MediaFormat entity by IDs.
func (_u *MediaUpdate) AddFormatIDs(ids ...uuid.UUID) *MediaUpdate {
	_u.mutation.AddFormatIDs(ids...)
	return _u
}

// AddFormats adds the "formats" edges to the MediaFormat entity.
func (_u *MediaUpdate) AddFormats(v ...*MediaFormat) *MediaUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFormatIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (_u *MediaUpdate) Mutation() *MediaMutation {
	return _u.mutation
}

// ClearFormats clears all "formats" edges to the MediaFormat entity.
func (_u *MediaUpdate) ClearFormats() *MediaUpdate {
	_u.mutation.ClearFormats()
	return _u
}

// RemoveFormatIDs removes the "formats" edge to MediaFormat entities by IDs.
func (_u *MediaUpdate) RemoveFormatIDs(ids ...uuid.UUID) *MediaUpdate {
	_u.mutation.RemoveFormatIDs(ids...)
	return _u
}

// RemoveFormats removes "formats" edges to MediaFormat entities.
func (_u *MediaUpdate) RemoveFormats(v ...*MediaFormat) *MediaUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFormatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := media.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := media.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Media.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := media.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Media.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := media.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Media.url": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(media.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(media.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(media.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(media.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(media.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(media.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(media.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(media.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(media.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(media.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(media.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(media.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(media.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(media.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(media.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlternativeText(); ok {
		_spec.SetField(media.FieldAlternativeText, field.TypeString, value)
	}
	if _u.mutation.AlternativeTextCleared() {
		_spec.ClearField(media.FieldAlternativeText, field.TypeString)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(media.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(media.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(media.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(media.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(media.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(media.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(media.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(media.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.Ext(); ok {
		_spec.SetField(media.FieldExt, field.TypeString, value)
	}
	if _u.mutation.ExtCleared() {
		_spec.ClearField(media.FieldExt, field.TypeString)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(media.FieldMime, field.TypeString, value)
	}
	if _u.mutation.MimeCleared() {
		_spec.ClearField(media.FieldMime, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(media.FieldSize, field.TypeFloat64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(media.FieldSize, field.TypeFloat64)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PreviewURL(); ok {
		_spec.SetField(media.FieldPreviewURL, field.TypeString, value)
	}
	if _u.mutation.PreviewURLCleared() {
		_spec.ClearField(media.FieldPreviewURL, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(media.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(media.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderMetadata(); ok {
		_spec.SetField(media.FieldProviderMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ProviderMetadataCleared() {
		_spec.ClearField(media.FieldProviderMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.FolderPath(); ok {
		_spec.SetField(media.FieldFolderPath, field.TypeString, value)
	}
	if _u.mutation.FolderPathCleared() {
		_spec.ClearField(media.FieldFolderPath, field.TypeString)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(media.FieldLocale, field.TypeString, value)
	}
	if _u.mutation.LocaleCleared() {
		_spec.ClearField(media.FieldLocale, field.TypeString)
	}
	if value, ok := _u.mutation.IsURLSigned(); ok {
		_spec.SetField(media.FieldIsURLSigned, field.TypeBool, value)
	}
	if _u.mutation.IsURLSignedCleared() {
		_spec.ClearField(media.FieldIsURLSigned, field.TypeBool)
	}
	if _u.mutation.FormatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFormatsIDs(); len(nodes) > 0 && !_u.mutation.FormatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FormatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaUpdateOne is the builder for updating a single Media entity.
type MediaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *MediaUpdateOne) SetTenantID(v string) *MediaUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableTenantID(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *MediaUpdateOne) SetUpdatedByID(v uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableUpdatedByID(v *uuid.UUID) *MediaUpdateOne {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *MediaUpdateOne) ClearUpdatedByID() *MediaUpdateOne {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaUpdateOne) SetUpdatedAt(v time.Time) *MediaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MediaUpdateOne) ClearUpdatedAt() *MediaUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *MediaUpdateOne) SetDeletedByID(v uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableDeletedByID(v *uuid.UUID) *MediaUpdateOne {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *MediaUpdateOne) ClearDeletedByID() *MediaUpdateOne {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MediaUpdateOne) SetDeletedAt(v time.Time) *MediaUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableDeletedAt(v *time.Time) *MediaUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MediaUpdateOne) ClearDeletedAt() *MediaUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MediaUpdateOne) SetPublishedAt(v time.Time) *MediaUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillablePublishedAt(v *time.Time) *MediaUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MediaUpdateOne) ClearPublishedAt() *MediaUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *MediaUpdateOne) SetArchivedAt(v time.Time) *MediaUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableArchivedAt(v *time.Time) *MediaUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *MediaUpdateOne) ClearArchivedAt() *MediaUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *MediaUpdateOne) SetName(v string) *MediaUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableName(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAlternativeText sets the "alternative_text" field.
func (_u *MediaUpdateOne) SetAlternativeText(v string) *MediaUpdateOne {
	_u.mutation.SetAlternativeText(v)
	return _u
}

// SetNillableAlternativeText sets the "alternative_text" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableAlternativeText(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetAlternativeText(*v)
	}
	return _u
}

// ClearAlternativeText clears the value of the "alternative_text" field.
func (_u *MediaUpdateOne) ClearAlternativeText() *MediaUpdateOne {
	_u.mutation.ClearAlternativeText()
	return _u
}

// SetCaption sets the "caption" field.
func (_u *MediaUpdateOne) SetCaption(v string) *MediaUpdateOne {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableCaption(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *MediaUpdateOne) ClearCaption() *MediaUpdateOne {
	_u.mutation.ClearCaption()
	return _u
}

// SetWidth sets the "width" field.
func (_u *MediaUpdateOne) SetWidth(v int) *MediaUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableWidth(v *int) *MediaUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *MediaUpdateOne) AddWidth(v int) *MediaUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *MediaUpdateOne) ClearWidth() *MediaUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *MediaUpdateOne) SetHeight(v int) *MediaUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableHeight(v *int) *MediaUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *MediaUpdateOne) AddHeight(v int) *MediaUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *MediaUpdateOne) ClearHeight() *MediaUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetHash sets the "hash" field.
func (_u *MediaUpdateOne) SetHash(v string) *MediaUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableHash(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *MediaUpdateOne) ClearHash() *MediaUpdateOne {
	_u.mutation.ClearHash()
	return _u
}

// SetExt sets the "ext" field.
func (_u *MediaUpdateOne) SetExt(v string) *MediaUpdateOne {
	_u.mutation.SetExt(v)
	return _u
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableExt(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetExt(*v)
	}
	return _u
}

// ClearExt clears the value of the "ext" field.
func (_u *MediaUpdateOne) ClearExt() *MediaUpdateOne {
	_u.mutation.ClearExt()
	return _u
}

// SetMime sets the "mime" field.
func (_u *MediaUpdateOne) SetMime(v string) *MediaUpdateOne {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableMime(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// ClearMime clears the value of the "mime" field.
func (_u *MediaUpdateOne) ClearMime() *MediaUpdateOne {
	_u.mutation.ClearMime()
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaUpdateOne) SetSize(v float64) *MediaUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableSize(v *float64) *MediaUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaUpdateOne) AddSize(v float64) *MediaUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *MediaUpdateOne) ClearSize() *MediaUpdateOne {
	_u.mutation.ClearSize()
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaUpdateOne) SetURL(v string) *MediaUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableURL(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetPreviewURL sets the "preview_url" field.
func (_u *MediaUpdateOne) SetPreviewURL(v string) *MediaUpdateOne {
	_u.mutation.SetPreviewURL(v)
	return _u
}

// SetNillablePreviewURL sets the "preview_url" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillablePreviewURL(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetPreviewURL(*v)
	}
	return _u
}

// ClearPreviewURL clears the value of the "preview_url" field.
func (_u *MediaUpdateOne) ClearPreviewURL() *MediaUpdateOne {
	_u.mutation.ClearPreviewURL()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *MediaUpdateOne) SetProvider(v string) *MediaUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableProvider(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *MediaUpdateOne) ClearProvider() *MediaUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetProviderMetadata sets the "provider_metadata" field.
func (_u *MediaUpdateOne) SetProviderMetadata(v map[string]interface{}) *MediaUpdateOne {
	_u.mutation.SetProviderMetadata(v)
	return _u
}

// ClearProviderMetadata clears the value of the "provider_metadata" field.
func (_u *MediaUpdateOne) ClearProviderMetadata() *MediaUpdateOne {
	_u.mutation.ClearProviderMetadata()
	return _u
}

// SetFolderPath sets the "folder_path" field.
func (_u *MediaUpdateOne) SetFolderPath(v string) *MediaUpdateOne {
	_u.mutation.SetFolderPath(v)
	return _u
}

// SetNillableFolderPath sets the "folder_path" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableFolderPath(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetFolderPath(*v)
	}
	return _u
}

// ClearFolderPath clears the value of the "folder_path" field.
func (_u *MediaUpdateOne) ClearFolderPath() *MediaUpdateOne {
	_u.mutation.ClearFolderPath()
	return _u
}

// SetLocale sets the "locale" field.
func (_u *MediaUpdateOne) SetLocale(v string) *MediaUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableLocale(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// ClearLocale clears the value of the "locale" field.
func (_u *MediaUpdateOne) ClearLocale() *MediaUpdateOne {
	_u.mutation.ClearLocale()
	return _u
}

// SetIsURLSigned sets the "is_url_signed" field.
func (_u *MediaUpdateOne) SetIsURLSigned(v bool) *MediaUpdateOne {
	_u.mutation.SetIsURLSigned(v)
	return _u
}

// SetNillableIsURLSigned sets the "is_url_signed" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableIsURLSigned(v *bool) *MediaUpdateOne {
	if v != nil {
		_u.SetIsURLSigned(*v)
	}
	return _u
}

// ClearIsURLSigned clears the value of the "is_url_signed" field.
func (_u *MediaUpdateOne) ClearIsURLSigned() *MediaUpdateOne {
	_u.mutation.ClearIsURLSigned()
	return _u
}

// AddFormatIDs adds the "formats" edge to the MediaFormat entity by IDs.
func (_u *MediaUpdateOne) AddFormatIDs(ids ...uuid.UUID) *MediaUpdateOne {
	_u.mutation.AddFormatIDs(ids...)
	return _u
}

// AddFormats adds the "formats" edges to the MediaFormat entity.
func (_u *MediaUpdateOne) AddFormats(v ...*MediaFormat) *MediaUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFormatIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (_u *MediaUpdateOne) Mutation() *MediaMutation {
	return _u.mutation
}

// ClearFormats clears all "formats" edges to the MediaFormat entity.
func (_u *MediaUpdateOne) ClearFormats() *MediaUpdateOne {
	_u.mutation.ClearFormats()
	return _u
}

// RemoveFormatIDs removes the "formats" edge to MediaFormat entities by IDs.
func (_u *MediaUpdateOne) RemoveFormatIDs(ids ...uuid.UUID) *MediaUpdateOne {
	_u.mutation.RemoveFormatIDs(ids...)
	return _u
}

// RemoveFormats removes "formats" edges to MediaFormat entities.
func (_u *MediaUpdateOne) RemoveFormats(v ...*MediaFormat) *MediaUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFormatIDs(ids...)
}

// Where appends a list predicates to the MediaUpdate builder.
func (_u *MediaUpdateOne) Where(ps ...predicate.Media) *MediaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaUpdateOne) Select(field string, fields ...string) *MediaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Media entity.
func (_u *MediaUpdateOne) Save(ctx context.Context) (*Media, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaUpdateOne) SaveX(ctx context.Context) *Media {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := media.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := media.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Media.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := media.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Media.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := media.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Media.url": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaUpdateOne) sqlSave(ctx context.Context) (_node *Media, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Media.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, media.FieldID)
		for _, f := range fields {
			if !media.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != media.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(media.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(media.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(media.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(media.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(media.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(media.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(media.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(media.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(media.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(media.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(media.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(media.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(media.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(media.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(media.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlternativeText(); ok {
		_spec.SetField(media.FieldAlternativeText, field.TypeString, value)
	}
	if _u.mutation.AlternativeTextCleared() {
		_spec.ClearField(media.FieldAlternativeText, field.TypeString)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(media.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(media.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(media.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(media.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(media.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(media.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(media.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(media.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.Ext(); ok {
		_spec.SetField(media.FieldExt, field.TypeString, value)
	}
	if _u.mutation.ExtCleared() {
		_spec.ClearField(media.FieldExt, field.TypeString)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(media.FieldMime, field.TypeString, value)
	}
	if _u.mutation.MimeCleared() {
		_spec.ClearField(media.FieldMime, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(media.FieldSize, field.TypeFloat64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(media.FieldSize, field.TypeFloat64)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PreviewURL(); ok {
		_spec.SetField(media.FieldPreviewURL, field.TypeString, value)
	}
	if _u.mutation.PreviewURLCleared() {
		_spec.ClearField(media.FieldPreviewURL, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(media.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(media.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderMetadata(); ok {
		_spec.SetField(media.FieldProviderMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ProviderMetadataCleared() {
		_spec.ClearField(media.FieldProviderMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.FolderPath(); ok {
		_spec.SetField(media.FieldFolderPath, field.TypeString, value)
	}
	if _u.mutation.FolderPathCleared() {
		_spec.ClearField(media.FieldFolderPath, field.TypeString)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(media.FieldLocale, field.TypeString, value)
	}
	if _u.mutation.LocaleCleared() {
		_spec.ClearField(media.FieldLocale, field.TypeString)
	}
	if value, ok := _u.mutation.IsURLSigned(); ok {
		_spec.SetField(media.FieldIsURLSigned, field.TypeBool, value)
	}
	if _u.mutation.IsURLSignedCleared() {
		_spec.ClearField(media.FieldIsURLSigned, field.TypeBool)
	}
	if _u.mutation.FormatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFormatsIDs(); len(nodes) > 0 && !_u.mutation.FormatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FormatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Media{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
