// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
)

// MediaFormatCreate is the builder for creating a MediaFormat entity.
type MediaFormatCreate struct {
	config
	mutation *MediaFormatMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *MediaFormatCreate) SetTenantID(v string) *MediaFormatCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableTenantID(v *string) *MediaFormatCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedByID sets the "created_by_id" field.
func (_c *MediaFormatCreate) SetCreatedByID(v uuid.UUID) *MediaFormatCreate {
	_c.mutation.SetCreatedByID(v)
	return _c
}

// SetNillableCreatedByID sets the "created_by_id" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableCreatedByID(v *uuid.UUID) *MediaFormatCreate {
	if v != nil {
		_c.SetCreatedByID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaFormatCreate) SetCreatedAt(v time.Time) *MediaFormatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableCreatedAt(v *time.Time) *MediaFormatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_c *MediaFormatCreate) SetUpdatedByID(v uuid.UUID) *MediaFormatCreate {
	_c.mutation.SetUpdatedByID(v)
	return _c
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableUpdatedByID(v *uuid.UUID) *MediaFormatCreate {
	if v != nil {
		_c.SetUpdatedByID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaFormatCreate) SetUpdatedAt(v time.Time) *MediaFormatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableUpdatedAt(v *time.Time) *MediaFormatCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_c *MediaFormatCreate) SetDeletedByID(v uuid.UUID) *MediaFormatCreate {
	_c.mutation.SetDeletedByID(v)
	return _c
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableDeletedByID(v *uuid.UUID) *MediaFormatCreate {
	if v != nil {
		_c.SetDeletedByID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MediaFormatCreate) SetDeletedAt(v time.Time) *MediaFormatCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableDeletedAt(v *time.Time) *MediaFormatCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *MediaFormatCreate) SetPublishedAt(v time.Time) *MediaFormatCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillablePublishedAt(v *time.Time) *MediaFormatCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetArchivedAt sets the "archived_at" field.
func (_c *MediaFormatCreate) SetArchivedAt(v time.Time) *MediaFormatCreate {
	_c.mutation.SetArchivedAt(v)
	return _c
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableArchivedAt(v *time.Time) *MediaFormatCreate {
	if v != nil {
		_c.SetArchivedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *MediaFormatCreate) SetName(v string) *MediaFormatCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetExt sets the "ext" field.
func (_c *MediaFormatCreate) SetExt(v string) *MediaFormatCreate {
	_c.mutation.SetExt(v)
	return _c
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableExt(v *string) *MediaFormatCreate {
	if v != nil {
		_c.SetExt(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MediaFormatCreate) SetURL(v string) *MediaFormatCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetHash sets the "hash" field.
func (_c *MediaFormatCreate) SetHash(v string) *MediaFormatCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableHash(v *string) *MediaFormatCreate {
	if v != nil {
		_c.SetHash(*v)
	}
	return _c
}

// SetMime sets the "mime" field.
func (_c *MediaFormatCreate) SetMime(v string) *MediaFormatCreate {
	_c.mutation.SetMime(v)
	return _c
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableMime(v *string) *MediaFormatCreate {
	if v != nil {
		_c.SetMime(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *MediaFormatCreate) SetSize(v float64) *MediaFormatCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableSize(v *float64) *MediaFormatCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetSizeInBytes sets the "size_in_bytes" field.
func (_c *MediaFormatCreate) SetSizeInBytes(v int64) *MediaFormatCreate {
	_c.mutation.SetSizeInBytes(v)
	return _c
}

// SetNillableSizeInBytes sets the "size_in_bytes" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableSizeInBytes(v *int64) *MediaFormatCreate {
	if v != nil {
		_c.SetSizeInBytes(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *MediaFormatCreate) SetWidth(v int) *MediaFormatCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableWidth(v *int) *MediaFormatCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *MediaFormatCreate) SetHeight(v int) *MediaFormatCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableHeight(v *int) *MediaFormatCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetProviderMetadata sets the "provider_metadata" field.
func (_c *MediaFormatCreate) SetProviderMetadata(v map[string]interface{}) *MediaFormatCreate {
	_c.mutation.SetProviderMetadata(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *MediaFormatCreate) SetPath(v string) *MediaFormatCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillablePath(v *string) *MediaFormatCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetIsURLSigned sets the "is_url_signed" field.
func (_c *MediaFormatCreate) SetIsURLSigned(v bool) *MediaFormatCreate {
	_c.mutation.SetIsURLSigned(v)
	return _c
}

// SetNillableIsURLSigned sets the "is_url_signed" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableIsURLSigned(v *bool) *MediaFormatCreate {
	if v != nil {
		_c.SetIsURLSigned(*v)
	}
	return _c
}

// SetMediaID sets the "media_id" field.
func (_c *MediaFormatCreate) SetMediaID(v uuid.UUID) *MediaFormatCreate {
	_c.mutation.SetMediaID(v)
	return _c
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableMediaID(v *uuid.UUID) *MediaFormatCreate {
	if v != nil {
		_c.SetMediaID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaFormatCreate) SetID(v uuid.UUID) *MediaFormatCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaFormatCreate) SetNillableID(v *uuid.UUID) *MediaFormatCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetMedia sets the "media" edge to the Media entity.
func (_c *MediaFormatCreate) SetMedia(v *Media) *MediaFormatCreate {
	return _c.SetMediaID(v.ID)
}

// Mutation returns the MediaFormatMutation object of the builder.
func (_c *MediaFormatCreate) Mutation() *MediaFormatMutation {
	return _c.mutation
}

// Save creates the MediaFormat in the database.
func (_c *MediaFormatCreate) Save(ctx context.Context) (*MediaFormat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaFormatCreate) SaveX(ctx context.Context) *MediaFormat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaFormatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaFormatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaFormatCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := mediaformat.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediaformat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediaformat.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mediaformat.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaFormatCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "MediaFormat.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := mediaformat.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MediaFormat.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := mediaformat.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "MediaFormat.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := mediaformat.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.url": %w`, err)}
		}
	}
	return nil
}

func (_c *MediaFormatCreate) sqlSave(ctx context.Context) (*MediaFormat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaFormatCreate) createSpec() (*MediaFormat, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaFormat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaformat.Table, sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(mediaformat.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedByID(); ok {
		_spec.SetField(mediaformat.FieldCreatedByID, field.TypeUUID, value)
		_node.CreatedByID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediaformat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedByID(); ok {
		_spec.SetField(mediaformat.FieldUpdatedByID, field.TypeUUID, value)
		_node.UpdatedByID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaformat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedByID(); ok {
		_spec.SetField(mediaformat.FieldDeletedByID, field.TypeUUID, value)
		_node.DeletedByID = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(mediaformat.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(mediaformat.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.ArchivedAt(); ok {
		_spec.SetField(mediaformat.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(mediaformat.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Ext(); ok {
		_spec.SetField(mediaformat.FieldExt, field.TypeString, value)
		_node.Ext = &value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(mediaformat.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(mediaformat.FieldHash, field.TypeString, value)
		_node.Hash = &value
	}
	if value, ok := _c.mutation.Mime(); ok {
		_spec.SetField(mediaformat.FieldMime, field.TypeString, value)
		_node.Mime = &value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(mediaformat.FieldSize, field.TypeFloat64, value)
		_node.Size = &value
	}
	if value, ok := _c.mutation.SizeInBytes(); ok {
		_spec.SetField(mediaformat.FieldSizeInBytes, field.TypeInt64, value)
		_node.SizeInBytes = &value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(mediaformat.FieldWidth, field.TypeInt, value)
		_node.Width = &value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(mediaformat.FieldHeight, field.TypeInt, value)
		_node.Height = &value
	}
	if value, ok := _c.mutation.ProviderMetadata(); ok {
		_spec.SetField(mediaformat.FieldProviderMetadata, field.TypeJSON, value)
		_node.ProviderMetadata = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(mediaformat.FieldPath, field.TypeString, value)
		_node.Path = &value
	}
	if value, ok := _c.mutation.IsURLSigned(); ok {
		_spec.SetField(mediaformat.FieldIsURLSigned, field.TypeBool, value)
		_node.IsURLSigned = &value
	}
	if nodes := _c.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaformat.MediaTable,
			Columns: []string{mediaformat.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MediaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaFormatCreateBulk is the builder for creating many MediaFormat entities in bulk.
type MediaFormatCreateBulk struct {
	config
	err      error
	builders []*MediaFormatCreate
}

// Save creates the MediaFormat entities in the database.
func (_c *MediaFormatCreateBulk) Save(ctx context.Context) ([]*MediaFormat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaFormat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaFormatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaFormatCreateBulk) SaveX(ctx context.Context) []*MediaFormat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaFormatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaFormatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
