// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
)

// MediaCreate is the builder for creating a Media entity.
type MediaCreate struct {
	config
	mutation *MediaMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *MediaCreate) SetTenantID(v string) *MediaCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *MediaCreate) SetNillableTenantID(v *string) *MediaCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedByID sets the "created_by_id" field.
func (_c *MediaCreate) SetCreatedByID(v uuid.UUID) *MediaCreate {
	_c.mutation.SetCreatedByID(v)
	return _c
}

// SetNillableCreatedByID sets the "created_by_id" field if the given value is not nil.
func (_c *MediaCreate) SetNillableCreatedByID(v *uuid.UUID) *MediaCreate {
	if v != nil {
		_c.SetCreatedByID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaCreate) SetCreatedAt(v time.Time) *MediaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableCreatedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_c *MediaCreate) SetUpdatedByID(v uuid.UUID) *MediaCreate {
	_c.mutation.SetUpdatedByID(v)
	return _c
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_c *MediaCreate) SetNillableUpdatedByID(v *uuid.UUID) *MediaCreate {
	if v != nil {
		_c.SetUpdatedByID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaCreate) SetUpdatedAt(v time.Time) *MediaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableUpdatedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_c *MediaCreate) SetDeletedByID(v uuid.UUID) *MediaCreate {
	_c.mutation.SetDeletedByID(v)
	return _c
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_c *MediaCreate) SetNillableDeletedByID(v *uuid.UUID) *MediaCreate {
	if v != nil {
		_c.SetDeletedByID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MediaCreate) SetDeletedAt(v time.Time) *MediaCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableDeletedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *MediaCreate) SetPublishedAt(v time.Time) *MediaCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillablePublishedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetArchivedAt sets the "archived_at" field.
func (_c *MediaCreate) SetArchivedAt(v time.Time) *MediaCreate {
	_c.mutation.SetArchivedAt(v)
	return _c
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableArchivedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetArchivedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *MediaCreate) SetName(v string) *MediaCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAlternativeText sets the "alternative_text" field.
func (_c *MediaCreate) SetAlternativeText(v string) *MediaCreate {
	_c.mutation.SetAlternativeText(v)
	return _c
}

// SetNillableAlternativeText sets the "alternative_text" field if the given value is not nil.
func (_c *MediaCreate) SetNillableAlternativeText(v *string) *MediaCreate {
	if v != nil {
		_c.SetAlternativeText(*v)
	}
	return _c
}

// SetCaption sets the "caption" field.
func (_c *MediaCreate) SetCaption(v string) *MediaCreate {
	_c.mutation.SetCaption(v)
	return _c
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_c *MediaCreate) SetNillableCaption(v *string) *MediaCreate {
	if v != nil {
		_c.SetCaption(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *MediaCreate) SetWidth(v int) *MediaCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *MediaCreate) SetNillableWidth(v *int) *MediaCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *MediaCreate) SetHeight(v int) *MediaCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *MediaCreate) SetNillableHeight(v *int) *MediaCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *MediaCreate) SetHash(v string) *MediaCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_c *MediaCreate) SetNillableHash(v *string) *MediaCreate {
	if v != nil {
		_c.SetHash(*v)
	}
	return _c
}

// SetExt sets the "ext" field.
func (_c *MediaCreate) SetExt(v string) *MediaCreate {
	_c.mutation.SetExt(v)
	return _c
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (_c *MediaCreate) SetNillableExt(v *string) *MediaCreate {
	if v != nil {
		_c.SetExt(*v)
	}
	return _c
}

// SetMime sets the "mime" field.
func (_c *MediaCreate) SetMime(v string) *MediaCreate {
	_c.mutation.SetMime(v)
	return _c
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_c *MediaCreate) SetNillableMime(v *string) *MediaCreate {
	if v != nil {
		_c.SetMime(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *MediaCreate) SetSize(v float64) *MediaCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *MediaCreate) SetNillableSize(v *float64) *MediaCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MediaCreate) SetURL(v string) *MediaCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetPreviewURL sets the "preview_url" field.
func (_c *MediaCreate) SetPreviewURL(v string) *MediaCreate {
	_c.mutation.SetPreviewURL(v)
	return _c
}

// SetNillablePreviewURL sets the "preview_url" field if the given value is not nil.
func (_c *MediaCreate) SetNillablePreviewURL(v *string) *MediaCreate {
	if v != nil {
		_c.SetPreviewURL(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *MediaCreate) SetProvider(v string) *MediaCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *MediaCreate) SetNillableProvider(v *string) *MediaCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetProviderMetadata sets the "provider_metadata" field.
func (_c *MediaCreate) SetProviderMetadata(v map[string]interface{}) *MediaCreate {
	_c.mutation.SetProviderMetadata(v)
	return _c
}

// SetFolderPath sets the "folder_path" field.
func (_c *MediaCreate) SetFolderPath(v string) *MediaCreate {
	_c.mutation.SetFolderPath(v)
	return _c
}

// SetNillableFolderPath sets the "folder_path" field if the given value is not nil.
func (_c *MediaCreate) SetNillableFolderPath(v *string) *MediaCreate {
	if v != nil {
		_c.SetFolderPath(*v)
	}
	return _c
}

// SetLocale sets the "locale" field.
func (_c *MediaCreate) SetLocale(v string) *MediaCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_c *MediaCreate) SetNillableLocale(v *string) *MediaCreate {
	if v != nil {
		_c.SetLocale(*v)
	}
	return _c
}

// SetIsURLSigned sets the "is_url_signed" field.
func (_c *MediaCreate) SetIsURLSigned(v bool) *MediaCreate {
	_c.mutation.SetIsURLSigned(v)
	return _c
}

// SetNillableIsURLSigned sets the "is_url_signed" field if the given value is not nil.
func (_c *MediaCreate) SetNillableIsURLSigned(v *bool) *MediaCreate {
	if v != nil {
		_c.SetIsURLSigned(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaCreate) SetID(v uuid.UUID) *MediaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaCreate) SetNillableID(v *uuid.UUID) *MediaCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddFormatIDs adds the "formats" edge to the MediaFormat entity by IDs.
func (_c *MediaCreate) AddFormatIDs(ids ...uuid.UUID) *MediaCreate {
	_c.mutation.AddFormatIDs(ids...)
	return _c
}

// AddFormats adds the "formats" edges to the MediaFormat entity.
func (_c *MediaCreate) AddFormats(v ...*MediaFormat) *MediaCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFormatIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (_c *MediaCreate) Mutation() *MediaMutation {
	return _c.mutation
}

// Save creates the Media in the database.
func (_c *MediaCreate) Save(ctx context.Context) (*Media, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaCreate) SaveX(ctx context.Context) *Media {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := media.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := media.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := media.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := media.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Media.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := media.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Media.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Media.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := media.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Media.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Media.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := media.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Media.url": %w`, err)}
		}
	}
	return nil
}

func (_c *MediaCreate) sqlSave(ctx context.Context) (*Media, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaCreate) createSpec() (*Media, *sqlgraph.CreateSpec) {
	var (
		_node = &Media{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(media.Table, sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(media.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedByID(); ok {
		_spec.SetField(media.FieldCreatedByID, field.TypeUUID, value)
		_node.CreatedByID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(media.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedByID(); ok {
		_spec.SetField(media.FieldUpdatedByID, field.TypeUUID, value)
		_node.UpdatedByID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedByID(); ok {
		_spec.SetField(media.FieldDeletedByID, field.TypeUUID, value)
		_node.DeletedByID = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(media.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(media.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.ArchivedAt(); ok {
		_spec.SetField(media.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(media.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AlternativeText(); ok {
		_spec.SetField(media.FieldAlternativeText, field.TypeString, value)
		_node.AlternativeText = &value
	}
	if value, ok := _c.mutation.Caption(); ok {
		_spec.SetField(media.FieldCaption, field.TypeString, value)
		_node.Caption = &value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt, value)
		_node.Width = &value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt, value)
		_node.Height = &value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(media.FieldHash, field.TypeString, value)
		_node.Hash = &value
	}
	if value, ok := _c.mutation.Ext(); ok {
		_spec.SetField(media.FieldExt, field.TypeString, value)
		_node.Ext = &value
	}
	if value, ok := _c.mutation.Mime(); ok {
		_spec.SetField(media.FieldMime, field.TypeString, value)
		_node.Mime = &value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeFloat64, value)
		_node.Size = &value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.PreviewURL(); ok {
		_spec.SetField(media.FieldPreviewURL, field.TypeString, value)
		_node.PreviewURL = &value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(media.FieldProvider, field.TypeString, value)
		_node.Provider = &value
	}
	if value, ok := _c.mutation.ProviderMetadata(); ok {
		_spec.SetField(media.FieldProviderMetadata, field.TypeJSON, value)
		_node.ProviderMetadata = value
	}
	if value, ok := _c.mutation.FolderPath(); ok {
		_spec.SetField(media.FieldFolderPath, field.TypeString, value)
		_node.FolderPath = &value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(media.FieldLocale, field.TypeString, value)
		_node.Locale = &value
	}
	if value, ok := _c.mutation.IsURLSigned(); ok {
		_spec.SetField(media.FieldIsURLSigned, field.TypeBool, value)
		_node.IsURLSigned = &value
	}
	if nodes := _c.mutation.FormatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.FormatsTable,
			Columns: []string{media.FormatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaCreateBulk is the builder for creating many Media entities in bulk.
type MediaCreateBulk struct {
	config
	err      error
	builders []*MediaCreate
}

// Save creates the Media entities in the database.
func (_c *MediaCreateBulk) Save(ctx context.Context) ([]*Media, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Media, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaCreateBulk) SaveX(ctx context.Context) []*Media {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
