// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
	"github.com/leeforge/framework/ent/predicate"
)

// MediaFormatUpdate is the builder for updating MediaFormat entities.
type MediaFormatUpdate struct {
	config
	hooks    []Hook
	mutation *MediaFormatMutation
}

// Where appends a list predicates to the MediaFormatUpdate builder.
func (_u *MediaFormatUpdate) Where(ps ...predicate.MediaFormat) *MediaFormatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *MediaFormatUpdate) SetTenantID(v string) *MediaFormatUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableTenantID(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *MediaFormatUpdate) SetUpdatedByID(v uuid.UUID) *MediaFormatUpdate {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableUpdatedByID(v *uuid.UUID) *MediaFormatUpdate {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *MediaFormatUpdate) ClearUpdatedByID() *MediaFormatUpdate {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaFormatUpdate) SetUpdatedAt(v time.Time) *MediaFormatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MediaFormatUpdate) ClearUpdatedAt() *MediaFormatUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *MediaFormatUpdate) SetDeletedByID(v uuid.UUID) *MediaFormatUpdate {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableDeletedByID(v *uuid.UUID) *MediaFormatUpdate {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *MediaFormatUpdate) ClearDeletedByID() *MediaFormatUpdate {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MediaFormatUpdate) SetDeletedAt(v time.Time) *MediaFormatUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableDeletedAt(v *time.Time) *MediaFormatUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MediaFormatUpdate) ClearDeletedAt() *MediaFormatUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MediaFormatUpdate) SetPublishedAt(v time.Time) *MediaFormatUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillablePublishedAt(v *time.Time) *MediaFormatUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MediaFormatUpdate) ClearPublishedAt() *MediaFormatUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *MediaFormatUpdate) SetArchivedAt(v time.Time) *MediaFormatUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableArchivedAt(v *time.Time) *MediaFormatUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *MediaFormatUpdate) ClearArchivedAt() *MediaFormatUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *MediaFormatUpdate) SetName(v string) *MediaFormatUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableName(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExt sets the "ext" field.
func (_u *MediaFormatUpdate) SetExt(v string) *MediaFormatUpdate {
	_u.mutation.SetExt(v)
	return _u
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableExt(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetExt(*v)
	}
	return _u
}

// ClearExt clears the value of the "ext" field.
func (_u *MediaFormatUpdate) ClearExt() *MediaFormatUpdate {
	_u.mutation.ClearExt()
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaFormatUpdate) SetURL(v string) *MediaFormatUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableURL(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *MediaFormatUpdate) SetHash(v string) *MediaFormatUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableHash(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *MediaFormatUpdate) ClearHash() *MediaFormatUpdate {
	_u.mutation.ClearHash()
	return _u
}

// SetMime sets the "mime" field.
func (_u *MediaFormatUpdate) SetMime(v string) *MediaFormatUpdate {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableMime(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// ClearMime clears the value of the "mime" field.
func (_u *MediaFormatUpdate) ClearMime() *MediaFormatUpdate {
	_u.mutation.ClearMime()
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaFormatUpdate) SetSize(v float64) *MediaFormatUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableSize(v *float64) *MediaFormatUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaFormatUpdate) AddSize(v float64) *MediaFormatUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *MediaFormatUpdate) ClearSize() *MediaFormatUpdate {
	_u.mutation.ClearSize()
	return _u
}

// SetSizeInBytes sets the "size_in_bytes" field.
func (_u *MediaFormatUpdate) SetSizeInBytes(v int64) *MediaFormatUpdate {
	_u.mutation.ResetSizeInBytes()
	_u.mutation.SetSizeInBytes(v)
	return _u
}

// SetNillableSizeInBytes sets the "size_in_bytes" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableSizeInBytes(v *int64) *MediaFormatUpdate {
	if v != nil {
		_u.SetSizeInBytes(*v)
	}
	return _u
}

// AddSizeInBytes adds value to the "size_in_bytes" field.
func (_u *MediaFormatUpdate) AddSizeInBytes(v int64) *MediaFormatUpdate {
	_u.mutation.AddSizeInBytes(v)
	return _u
}

// ClearSizeInBytes clears the value of the "size_in_bytes" field.
func (_u *MediaFormatUpdate) ClearSizeInBytes() *MediaFormatUpdate {
	_u.mutation.ClearSizeInBytes()
	return _u
}

// SetWidth sets the "width" field.
func (_u *MediaFormatUpdate) SetWidth(v int) *MediaFormatUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableWidth(v *int) *MediaFormatUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *MediaFormatUpdate) AddWidth(v int) *MediaFormatUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *MediaFormatUpdate) ClearWidth() *MediaFormatUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *MediaFormatUpdate) SetHeight(v int) *MediaFormatUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableHeight(v *int) *MediaFormatUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *MediaFormatUpdate) AddHeight(v int) *MediaFormatUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *MediaFormatUpdate) ClearHeight() *MediaFormatUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetProviderMetadata sets the "provider_metadata" field.
func (_u *MediaFormatUpdate) SetProviderMetadata(v map[string]interface{}) *MediaFormatUpdate {
	_u.mutation.SetProviderMetadata(v)
	return _u
}

// ClearProviderMetadata clears the value of the "provider_metadata" field.
func (_u *MediaFormatUpdate) ClearProviderMetadata() *MediaFormatUpdate {
	_u.mutation.ClearProviderMetadata()
	return _u
}

// SetPath sets the "path" field.
func (_u *MediaFormatUpdate) SetPath(v string) *MediaFormatUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillablePath(v *string) *MediaFormatUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *MediaFormatUpdate) ClearPath() *MediaFormatUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetIsURLSigned sets the "is_url_signed" field.
func (_u *MediaFormatUpdate) SetIsURLSigned(v bool) *MediaFormatUpdate {
	_u.mutation.SetIsURLSigned(v)
	return _u
}

// SetNillableIsURLSigned sets the "is_url_signed" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableIsURLSigned(v *bool) *MediaFormatUpdate {
	if v != nil {
		_u.SetIsURLSigned(*v)
	}
	return _u
}

// ClearIsURLSigned clears the value of the "is_url_signed" field.
func (_u *MediaFormatUpdate) ClearIsURLSigned() *MediaFormatUpdate {
	_u.mutation.ClearIsURLSigned()
	return _u
}

// SetMediaID sets the "media_id" field.
func (_u *MediaFormatUpdate) SetMediaID(v uuid.UUID) *MediaFormatUpdate {
	_u.mutation.SetMediaID(v)
	return _u
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_u *MediaFormatUpdate) SetNillableMediaID(v *uuid.UUID) *MediaFormatUpdate {
	if v != nil {
		_u.SetMediaID(*v)
	}
	return _u
}

// ClearMediaID clears the value of the "media_id" field.
func (_u *MediaFormatUpdate) ClearMediaID() *MediaFormatUpdate {
	_u.mutation.ClearMediaID()
	return _u
}

// SetMedia sets the "media" edge to the Media entity.
func (_u *MediaFormatUpdate) SetMedia(v *Media) *MediaFormatUpdate {
	return _u.SetMediaID(v.ID)
}

// Mutation returns the MediaFormatMutation object of the builder.
func (_u *MediaFormatUpdate) Mutation() *MediaFormatMutation {
	return _u.mutation
}

// ClearMedia clears the "media" edge to the Media entity.
func (_u *MediaFormatUpdate) ClearMedia() *MediaFormatUpdate {
	_u.mutation.ClearMedia()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaFormatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaFormatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaFormatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaFormatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaFormatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := mediaformat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaFormatUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := mediaformat.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mediaformat.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := mediaformat.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.url": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaFormatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaformat.Table, mediaformat.Columns, sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(mediaformat.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(mediaformat.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(mediaformat.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(mediaformat.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(mediaformat.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaformat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(mediaformat.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(mediaformat.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(mediaformat.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mediaformat.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mediaformat.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(mediaformat.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(mediaformat.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(mediaformat.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(mediaformat.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mediaformat.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ext(); ok {
		_spec.SetField(mediaformat.FieldExt, field.TypeString, value)
	}
	if _u.mutation.ExtCleared() {
		_spec.ClearField(mediaformat.FieldExt, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mediaformat.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(mediaformat.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(mediaformat.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(mediaformat.FieldMime, field.TypeString, value)
	}
	if _u.mutation.MimeCleared() {
		_spec.ClearField(mediaformat.FieldMime, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(mediaformat.FieldSize, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(mediaformat.FieldSize, field.TypeFloat64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(mediaformat.FieldSize, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SizeInBytes(); ok {
		_spec.SetField(mediaformat.FieldSizeInBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeInBytes(); ok {
		_spec.AddField(mediaformat.FieldSizeInBytes, field.TypeInt64, value)
	}
	if _u.mutation.SizeInBytesCleared() {
		_spec.ClearField(mediaformat.FieldSizeInBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(mediaformat.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(mediaformat.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(mediaformat.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(mediaformat.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(mediaformat.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(mediaformat.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.ProviderMetadata(); ok {
		_spec.SetField(mediaformat.FieldProviderMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ProviderMetadataCleared() {
		_spec.ClearField(mediaformat.FieldProviderMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(mediaformat.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(mediaformat.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.IsURLSigned(); ok {
		_spec.SetField(mediaformat.FieldIsURLSigned, field.TypeBool, value)
	}
	if _u.mutation.IsURLSignedCleared() {
		_spec.ClearField(mediaformat.FieldIsURLSigned, field.TypeBool)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaformat.MediaTable,
			Columns: []string{mediaformat.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaformat.MediaTable,
			Columns: []string{mediaformat.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaformat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaFormatUpdateOne is the builder for updating a single MediaFormat entity.
type MediaFormatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaFormatMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *MediaFormatUpdateOne) SetTenantID(v string) *MediaFormatUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableTenantID(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *MediaFormatUpdateOne) SetUpdatedByID(v uuid.UUID) *MediaFormatUpdateOne {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableUpdatedByID(v *uuid.UUID) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *MediaFormatUpdateOne) ClearUpdatedByID() *MediaFormatUpdateOne {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaFormatUpdateOne) SetUpdatedAt(v time.Time) *MediaFormatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MediaFormatUpdateOne) ClearUpdatedAt() *MediaFormatUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *MediaFormatUpdateOne) SetDeletedByID(v uuid.UUID) *MediaFormatUpdateOne {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableDeletedByID(v *uuid.UUID) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *MediaFormatUpdateOne) ClearDeletedByID() *MediaFormatUpdateOne {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MediaFormatUpdateOne) SetDeletedAt(v time.Time) *MediaFormatUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableDeletedAt(v *time.Time) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MediaFormatUpdateOne) ClearDeletedAt() *MediaFormatUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MediaFormatUpdateOne) SetPublishedAt(v time.Time) *MediaFormatUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillablePublishedAt(v *time.Time) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MediaFormatUpdateOne) ClearPublishedAt() *MediaFormatUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *MediaFormatUpdateOne) SetArchivedAt(v time.Time) *MediaFormatUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableArchivedAt(v *time.Time) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *MediaFormatUpdateOne) ClearArchivedAt() *MediaFormatUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *MediaFormatUpdateOne) SetName(v string) *MediaFormatUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableName(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExt sets the "ext" field.
func (_u *MediaFormatUpdateOne) SetExt(v string) *MediaFormatUpdateOne {
	_u.mutation.SetExt(v)
	return _u
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableExt(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetExt(*v)
	}
	return _u
}

// ClearExt clears the value of the "ext" field.
func (_u *MediaFormatUpdateOne) ClearExt() *MediaFormatUpdateOne {
	_u.mutation.ClearExt()
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaFormatUpdateOne) SetURL(v string) *MediaFormatUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableURL(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *MediaFormatUpdateOne) SetHash(v string) *MediaFormatUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableHash(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *MediaFormatUpdateOne) ClearHash() *MediaFormatUpdateOne {
	_u.mutation.ClearHash()
	return _u
}

// SetMime sets the "mime" field.
func (_u *MediaFormatUpdateOne) SetMime(v string) *MediaFormatUpdateOne {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableMime(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// ClearMime clears the value of the "mime" field.
func (_u *MediaFormatUpdateOne) ClearMime() *MediaFormatUpdateOne {
	_u.mutation.ClearMime()
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaFormatUpdateOne) SetSize(v float64) *MediaFormatUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableSize(v *float64) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaFormatUpdateOne) AddSize(v float64) *MediaFormatUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *MediaFormatUpdateOne) ClearSize() *MediaFormatUpdateOne {
	_u.mutation.ClearSize()
	return _u
}

// SetSizeInBytes sets the "size_in_bytes" field.
func (_u *MediaFormatUpdateOne) SetSizeInBytes(v int64) *MediaFormatUpdateOne {
	_u.mutation.ResetSizeInBytes()
	_u.mutation.SetSizeInBytes(v)
	return _u
}

// SetNillableSizeInBytes sets the "size_in_bytes" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableSizeInBytes(v *int64) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetSizeInBytes(*v)
	}
	return _u
}

// AddSizeInBytes adds value to the "size_in_bytes" field.
func (_u *MediaFormatUpdateOne) AddSizeInBytes(v int64) *MediaFormatUpdateOne {
	_u.mutation.AddSizeInBytes(v)
	return _u
}

// ClearSizeInBytes clears the value of the "size_in_bytes" field.
func (_u *MediaFormatUpdateOne) ClearSizeInBytes() *MediaFormatUpdateOne {
	_u.mutation.ClearSizeInBytes()
	return _u
}

// SetWidth sets the "width" field.
func (_u *MediaFormatUpdateOne) SetWidth(v int) *MediaFormatUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableWidth(v *int) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *MediaFormatUpdateOne) AddWidth(v int) *MediaFormatUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *MediaFormatUpdateOne) ClearWidth() *MediaFormatUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *MediaFormatUpdateOne) SetHeight(v int) *MediaFormatUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableHeight(v *int) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *MediaFormatUpdateOne) AddHeight(v int) *MediaFormatUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *MediaFormatUpdateOne) ClearHeight() *MediaFormatUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetProviderMetadata sets the "provider_metadata" field.
func (_u *MediaFormatUpdateOne) SetProviderMetadata(v map[string]interface{}) *MediaFormatUpdateOne {
	_u.mutation.SetProviderMetadata(v)
	return _u
}

// ClearProviderMetadata clears the value of the "provider_metadata" field.
func (_u *MediaFormatUpdateOne) ClearProviderMetadata() *MediaFormatUpdateOne {
	_u.mutation.ClearProviderMetadata()
	return _u
}

// SetPath sets the "path" field.
func (_u *MediaFormatUpdateOne) SetPath(v string) *MediaFormatUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillablePath(v *string) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *MediaFormatUpdateOne) ClearPath() *MediaFormatUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetIsURLSigned sets the "is_url_signed" field.
func (_u *MediaFormatUpdateOne) SetIsURLSigned(v bool) *MediaFormatUpdateOne {
	_u.mutation.SetIsURLSigned(v)
	return _u
}

// SetNillableIsURLSigned sets the "is_url_signed" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableIsURLSigned(v *bool) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetIsURLSigned(*v)
	}
	return _u
}

// ClearIsURLSigned clears the value of the "is_url_signed" field.
func (_u *MediaFormatUpdateOne) ClearIsURLSigned() *MediaFormatUpdateOne {
	_u.mutation.ClearIsURLSigned()
	return _u
}

// SetMediaID sets the "media_id" field.
func (_u *MediaFormatUpdateOne) SetMediaID(v uuid.UUID) *MediaFormatUpdateOne {
	_u.mutation.SetMediaID(v)
	return _u
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_u *MediaFormatUpdateOne) SetNillableMediaID(v *uuid.UUID) *MediaFormatUpdateOne {
	if v != nil {
		_u.SetMediaID(*v)
	}
	return _u
}

// ClearMediaID clears the value of the "media_id" field.
func (_u *MediaFormatUpdateOne) ClearMediaID() *MediaFormatUpdateOne {
	_u.mutation.ClearMediaID()
	return _u
}

// SetMedia sets the "media" edge to the Media entity.
func (_u *MediaFormatUpdateOne) SetMedia(v *Media) *MediaFormatUpdateOne {
	return _u.SetMediaID(v.ID)
}

// Mutation returns the MediaFormatMutation object of the builder.
func (_u *MediaFormatUpdateOne) Mutation() *MediaFormatMutation {
	return _u.mutation
}

// ClearMedia clears the "media" edge to the Media entity.
func (_u *MediaFormatUpdateOne) ClearMedia() *MediaFormatUpdateOne {
	_u.mutation.ClearMedia()
	return _u
}

// Where appends a list predicates to the MediaFormatUpdate builder.
func (_u *MediaFormatUpdateOne) Where(ps ...predicate.MediaFormat) *MediaFormatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaFormatUpdateOne) Select(field string, fields ...string) *MediaFormatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaFormat entity.
func (_u *MediaFormatUpdateOne) Save(ctx context.Context) (*MediaFormat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaFormatUpdateOne) SaveX(ctx context.Context) *MediaFormat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaFormatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaFormatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaFormatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := mediaformat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaFormatUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := mediaformat.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mediaformat.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := mediaformat.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MediaFormat.url": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaFormatUpdateOne) sqlSave(ctx context.Context) (_node *MediaFormat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaformat.Table, mediaformat.Columns, sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaFormat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaformat.FieldID)
		for _, f := range fields {
			if !mediaformat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaformat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(mediaformat.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(mediaformat.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(mediaformat.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(mediaformat.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(mediaformat.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaformat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(mediaformat.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(mediaformat.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(mediaformat.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mediaformat.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mediaformat.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(mediaformat.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(mediaformat.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(mediaformat.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(mediaformat.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mediaformat.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ext(); ok {
		_spec.SetField(mediaformat.FieldExt, field.TypeString, value)
	}
	if _u.mutation.ExtCleared() {
		_spec.ClearField(mediaformat.FieldExt, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mediaformat.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(mediaformat.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(mediaformat.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(mediaformat.FieldMime, field.TypeString, value)
	}
	if _u.mutation.MimeCleared() {
		_spec.ClearField(mediaformat.FieldMime, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(mediaformat.FieldSize, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(mediaformat.FieldSize, field.TypeFloat64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(mediaformat.FieldSize, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SizeInBytes(); ok {
		_spec.SetField(mediaformat.FieldSizeInBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeInBytes(); ok {
		_spec.AddField(mediaformat.FieldSizeInBytes, field.TypeInt64, value)
	}
	if _u.mutation.SizeInBytesCleared() {
		_spec.ClearField(mediaformat.FieldSizeInBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(mediaformat.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(mediaformat.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(mediaformat.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(mediaformat.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(mediaformat.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(mediaformat.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.ProviderMetadata(); ok {
		_spec.SetField(mediaformat.FieldProviderMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ProviderMetadataCleared() {
		_spec.ClearField(mediaformat.FieldProviderMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(mediaformat.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(mediaformat.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.IsURLSigned(); ok {
		_spec.SetField(mediaformat.FieldIsURLSigned, field.TypeBool, value)
	}
	if _u.mutation.IsURLSignedCleared() {
		_spec.ClearField(mediaformat.FieldIsURLSigned, field.TypeBool)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaformat.MediaTable,
			Columns: []string{mediaformat.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaformat.MediaTable,
			Columns: []string{mediaformat.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaFormat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaformat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
