// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
)

// MediaFormat is the model entity for the MediaFormat schema.
type MediaFormat struct {
	config `json:"-"`
	// ID of the ent.
	// 唯一标识
	ID uuid.UUID `json:"id,omitempty"`
	// 租户ID
	TenantID string `json:"tenant_id,omitempty"`
	// 创建者ID
	CreatedByID uuid.UUID `json:"created_by_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新者ID
	UpdatedByID uuid.UUID `json:"updated_by_id,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除者ID
	DeletedByID uuid.UUID `json:"deleted_by_id,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 发布时间
	PublishedAt time.Time `json:"published_at,omitempty"`
	// 归档时间
	ArchivedAt time.Time `json:"archived_at,omitempty"`
	// Format key such as thumbnail or small
	Name string `json:"name,omitempty"`
	// File extension including dot
	Ext *string `json:"ext,omitempty"`
	// Accessible URL or path
	URL string `json:"url,omitempty"`
	// Content hash used in filenames
	Hash *string `json:"hash,omitempty"`
	// MIME type
	Mime *string `json:"mime,omitempty"`
	// File size in MB
	Size *float64 `json:"size,omitempty"`
	// Exact file size in bytes
	SizeInBytes *int64 `json:"size_in_bytes,omitempty"`
	// Pixel width
	Width *int `json:"width,omitempty"`
	// Pixel height
	Height *int `json:"height,omitempty"`
	// Provider-specific metadata
	ProviderMetadata map[string]interface{} `json:"provider_metadata,omitempty"`
	// Provider-specific path
	Path *string `json:"path,omitempty"`
	// Whether generated URLs are signed
	IsURLSigned *bool `json:"is_url_signed,omitempty"`
	// Parent media ID
	MediaID uuid.UUID `json:"media_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaFormatQuery when eager-loading is set.
	Edges        MediaFormatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaFormatEdges holds the relations/edges for other nodes in the graph.
type MediaFormatEdges struct {
	// Media holds the value of the media edge.
	Media *Media `json:"media,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MediaOrErr returns the Media value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaFormatEdges) MediaOrErr() (*Media, error) {
	if e.Media != nil {
		return e.Media, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: media.Label}
	}
	return nil, &NotLoadedError{edge: "media"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaFormat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaformat.FieldProviderMetadata:
			values[i] = new([]byte)
		case mediaformat.FieldIsURLSigned:
			values[i] = new(sql.NullBool)
		case mediaformat.FieldSize:
			values[i] = new(sql.NullFloat64)
		case mediaformat.FieldSizeInBytes, mediaformat.FieldWidth, mediaformat.FieldHeight:
			values[i] = new(sql.NullInt64)
		case mediaformat.FieldTenantID, mediaformat.FieldName, mediaformat.FieldExt, mediaformat.FieldURL, mediaformat.FieldHash, mediaformat.FieldMime, mediaformat.FieldPath:
			values[i] = new(sql.NullString)
		case mediaformat.FieldCreatedAt, mediaformat.FieldUpdatedAt, mediaformat.FieldDeletedAt, mediaformat.FieldPublishedAt, mediaformat.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		case mediaformat.FieldID, mediaformat.FieldCreatedByID, mediaformat.FieldUpdatedByID, mediaformat.FieldDeletedByID, mediaformat.FieldMediaID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaFormat fields.
func (_m *MediaFormat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaformat.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mediaformat.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case mediaformat.FieldCreatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value != nil {
				_m.CreatedByID = *value
			}
		case mediaformat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediaformat.FieldUpdatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_id", values[i])
			} else if value != nil {
				_m.UpdatedByID = *value
			}
		case mediaformat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediaformat.FieldDeletedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by_id", values[i])
			} else if value != nil {
				_m.DeletedByID = *value
			}
		case mediaformat.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case mediaformat.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		case mediaformat.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = value.Time
			}
		case mediaformat.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case mediaformat.FieldExt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ext", values[i])
			} else if value.Valid {
				_m.Ext = new(string)
				*_m.Ext = value.String
			}
		case mediaformat.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case mediaformat.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = new(string)
				*_m.Hash = value.String
			}
		case mediaformat.FieldMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime", values[i])
			} else if value.Valid {
				_m.Mime = new(string)
				*_m.Mime = value.String
			}
		case mediaformat.FieldSize:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = new(float64)
				*_m.Size = value.Float64
			}
		case mediaformat.FieldSizeInBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_in_bytes", values[i])
			} else if value.Valid {
				_m.SizeInBytes = new(int64)
				*_m.SizeInBytes = value.Int64
			}
		case mediaformat.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = new(int)
				*_m.Width = int(value.Int64)
			}
		case mediaformat.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = new(int)
				*_m.Height = int(value.Int64)
			}
		case mediaformat.FieldProviderMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProviderMetadata); err != nil {
					return fmt.Errorf("unmarshal field provider_metadata: %w", err)
				}
			}
		case mediaformat.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = new(string)
				*_m.Path = value.String
			}
		case mediaformat.FieldIsURLSigned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_url_signed", values[i])
			} else if value.Valid {
				_m.IsURLSigned = new(bool)
				*_m.IsURLSigned = value.Bool
			}
		case mediaformat.FieldMediaID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field media_id", values[i])
			} else if value != nil {
				_m.MediaID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaFormat.
// This includes values selected through modifiers, order, etc.
func (_m *MediaFormat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMedia queries the "media" edge of the MediaFormat entity.
func (_m *MediaFormat) QueryMedia() *MediaQuery {
	return NewMediaFormatClient(_m.config).QueryMedia(_m)
}

// Update returns a builder for updating this MediaFormat.
// Note that you need to call MediaFormat.Unwrap() before calling this method if this MediaFormat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaFormat) Update() *MediaFormatUpdateOne {
	return NewMediaFormatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaFormat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaFormat) Unwrap() *MediaFormat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaFormat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaFormat) String() string {
	var builder strings.Builder
	builder.WriteString("MediaFormat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("created_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedByID))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedByID))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("archived_at=")
	builder.WriteString(_m.ArchivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Ext; v != nil {
		builder.WriteString("ext=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.Hash; v != nil {
		builder.WriteString("hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Mime; v != nil {
		builder.WriteString("mime=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Size; v != nil {
		builder.WriteString("size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SizeInBytes; v != nil {
		builder.WriteString("size_in_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Height; v != nil {
		builder.WriteString("height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("provider_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderMetadata))
	builder.WriteString(", ")
	if v := _m.Path; v != nil {
		builder.WriteString("path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IsURLSigned; v != nil {
		builder.WriteString("is_url_signed=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("media_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MediaID))
	builder.WriteByte(')')
	return builder.String()
}

// MediaFormats is a parsable slice of MediaFormat.
type MediaFormats []*MediaFormat
