// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
	"github.com/leeforge/framework/ent/predicate"
)

// MediaFormatQuery is the builder for querying MediaFormat entities.
type MediaFormatQuery struct {
	config
	ctx        *QueryContext
	order      []mediaformat.OrderOption
	inters     []Interceptor
	predicates []predicate.MediaFormat
	withMedia  *MediaQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MediaFormatQuery builder.
func (_q *MediaFormatQuery) Where(ps ...predicate.MediaFormat) *MediaFormatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MediaFormatQuery) Limit(limit int) *MediaFormatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MediaFormatQuery) Offset(offset int) *MediaFormatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MediaFormatQuery) Unique(unique bool) *MediaFormatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MediaFormatQuery) Order(o ...mediaformat.OrderOption) *MediaFormatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMedia chains the current query on the "media" edge.
func (_q *MediaFormatQuery) QueryMedia() *MediaQuery {
	query := (&MediaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaformat.Table, mediaformat.FieldID, selector),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaformat.MediaTable, mediaformat.MediaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MediaFormat entity from the query.
// Returns a *NotFoundError when no MediaFormat was found.
func (_q *MediaFormatQuery) First(ctx context.Context) (*MediaFormat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mediaformat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MediaFormatQuery) FirstX(ctx context.Context) *MediaFormat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MediaFormat ID from the query.
// Returns a *NotFoundError when no MediaFormat ID was found.
func (_q *MediaFormatQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mediaformat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MediaFormatQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MediaFormat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MediaFormat entity is found.
// Returns a *NotFoundError when no MediaFormat entities are found.
func (_q *MediaFormatQuery) Only(ctx context.Context) (*MediaFormat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mediaformat.Label}
	default:
		return nil, &NotSingularError{mediaformat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MediaFormatQuery) OnlyX(ctx context.Context) *MediaFormat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MediaFormat ID in the query.
// Returns a *NotSingularError when more than one MediaFormat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MediaFormatQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mediaformat.Label}
	default:
		err = &NotSingularError{mediaformat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MediaFormatQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MediaFormats.
func (_q *MediaFormatQuery) All(ctx context.Context) ([]*MediaFormat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MediaFormat, *MediaFormatQuery]()
	return withInterceptors[[]*MediaFormat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MediaFormatQuery) AllX(ctx context.Context) []*MediaFormat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MediaFormat IDs.
func (_q *MediaFormatQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(mediaformat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MediaFormatQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MediaFormatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MediaFormatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MediaFormatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MediaFormatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MediaFormatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MediaFormatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MediaFormatQuery) Clone() *MediaFormatQuery {
	if _q == nil {
		return nil
	}
	return &MediaFormatQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]mediaformat.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.MediaFormat{}, _q.predicates...),
		withMedia:  _q.withMedia.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMedia tells the query-builder to eager-load the nodes that are connected to
// the "media" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaFormatQuery) WithMedia(opts ...func(*MediaQuery)) *MediaFormatQuery {
	query := (&MediaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMedia = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MediaFormat.Query().
//		GroupBy(mediaformat.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MediaFormatQuery) GroupBy(field string, fields ...string) *MediaFormatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MediaFormatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = mediaformat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.MediaFormat.Query().
//		Select(mediaformat.FieldTenantID).
//		Scan(ctx, &v)
func (_q *MediaFormatQuery) Select(fields ...string) *MediaFormatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MediaFormatSelect{MediaFormatQuery: _q}
	sbuild.label = mediaformat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MediaFormatSelect configured with the given aggregations.
func (_q *MediaFormatQuery) Aggregate(fns ...AggregateFunc) *MediaFormatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MediaFormatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !mediaformat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MediaFormatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MediaFormat, error) {
	var (
		nodes       = []*MediaFormat{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withMedia != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MediaFormat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MediaFormat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMedia; query != nil {
		if err := _q.loadMedia(ctx, query, nodes, nil,
			func(n *MediaFormat, e *Media) { n.Edges.Media = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MediaFormatQuery) loadMedia(ctx context.Context, query *MediaQuery, nodes []*MediaFormat, init func(*MediaFormat), assign func(*MediaFormat, *Media)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MediaFormat)
	for i := range nodes {
		fk := nodes[i].MediaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(media.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "media_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MediaFormatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MediaFormatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mediaformat.Table, mediaformat.Columns, sqlgraph.NewFieldSpec(mediaformat.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaformat.FieldID)
		for i := range fields {
			if fields[i] != mediaformat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withMedia != nil {
			_spec.Node.AddColumnOnce(mediaformat.FieldMediaID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MediaFormatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(mediaformat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = mediaformat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MediaFormatGroupBy is the group-by builder for MediaFormat entities.
type MediaFormatGroupBy struct {
	selector
	build *MediaFormatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MediaFormatGroupBy) Aggregate(fns ...AggregateFunc) *MediaFormatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MediaFormatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaFormatQuery, *MediaFormatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MediaFormatGroupBy) sqlScan(ctx context.Context, root *MediaFormatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MediaFormatSelect is the builder for selecting fields of MediaFormat entities.
type MediaFormatSelect struct {
	*MediaFormatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MediaFormatSelect) Aggregate(fns ...AggregateFunc) *MediaFormatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MediaFormatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaFormatQuery, *MediaFormatSelect](ctx, _s.MediaFormatQuery, _s, _s.inters, v)
}

func (_s *MediaFormatSelect) sqlScan(ctx context.Context, root *MediaFormatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
