// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/casbinpolicy"
	"github.com/leeforge/framework/ent/media"
	"github.com/leeforge/framework/ent/mediaformat"
	"github.com/leeforge/framework/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	casbinpolicyFields := schema.CasbinPolicy{}.Fields()
	_ = casbinpolicyFields
	// casbinpolicyDescPtype is the schema descriptor for ptype field.
	casbinpolicyDescPtype := casbinpolicyFields[0].Descriptor()
	// casbinpolicy.PtypeValidator is a validator for the "ptype" field. It is called by the builders before save.
	casbinpolicy.PtypeValidator = func() func(string) error {
		validators := casbinpolicyDescPtype.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ptype string) error {
			for _, fn := range fns {
				if err := fn(ptype); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	mediaMixin := schema.Media{}.Mixin()
	mediaMixinFields0 := mediaMixin[0].Fields()
	_ = mediaMixinFields0
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescTenantID is the schema descriptor for tenant_id field.
	mediaDescTenantID := mediaMixinFields0[1].Descriptor()
	// media.DefaultTenantID holds the default value on creation for the tenant_id field.
	media.DefaultTenantID = mediaDescTenantID.Default.(string)
	// media.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	media.TenantIDValidator = mediaDescTenantID.Validators[0].(func(string) error)
	// mediaDescCreatedAt is the schema descriptor for created_at field.
	mediaDescCreatedAt := mediaMixinFields0[3].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the created_at field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	// mediaDescUpdatedAt is the schema descriptor for updated_at field.
	mediaDescUpdatedAt := mediaMixinFields0[5].Descriptor()
	// media.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	media.DefaultUpdatedAt = mediaDescUpdatedAt.Default.(func() time.Time)
	// media.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	media.UpdateDefaultUpdatedAt = mediaDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediaDescName is the schema descriptor for name field.
	mediaDescName := mediaFields[0].Descriptor()
	// media.NameValidator is a validator for the "name" field. It is called by the builders before save.
	media.NameValidator = mediaDescName.Validators[0].(func(string) error)
	// mediaDescURL is the schema descriptor for url field.
	mediaDescURL := mediaFields[9].Descriptor()
	// media.URLValidator is a validator for the "url" field. It is called by the builders before save.
	media.URLValidator = mediaDescURL.Validators[0].(func(string) error)
	// mediaDescID is the schema descriptor for id field.
	mediaDescID := mediaMixinFields0[0].Descriptor()
	// media.DefaultID holds the default value on creation for the id field.
	media.DefaultID = mediaDescID.Default.(func() uuid.UUID)
	mediaformatMixin := schema.MediaFormat{}.Mixin()
	mediaformatMixinFields0 := mediaformatMixin[0].Fields()
	_ = mediaformatMixinFields0
	mediaformatFields := schema.MediaFormat{}.Fields()
	_ = mediaformatFields
	// mediaformatDescTenantID is the schema descriptor for tenant_id field.
	mediaformatDescTenantID := mediaformatMixinFields0[1].Descriptor()
	// mediaformat.DefaultTenantID holds the default value on creation for the tenant_id field.
	mediaformat.DefaultTenantID = mediaformatDescTenantID.Default.(string)
	// mediaformat.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	mediaformat.TenantIDValidator = mediaformatDescTenantID.Validators[0].(func(string) error)
	// mediaformatDescCreatedAt is the schema descriptor for created_at field.
	mediaformatDescCreatedAt := mediaformatMixinFields0[3].Descriptor()
	// mediaformat.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediaformat.DefaultCreatedAt = mediaformatDescCreatedAt.Default.(func() time.Time)
	// mediaformatDescUpdatedAt is the schema descriptor for updated_at field.
	mediaformatDescUpdatedAt := mediaformatMixinFields0[5].Descriptor()
	// mediaformat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mediaformat.DefaultUpdatedAt = mediaformatDescUpdatedAt.Default.(func() time.Time)
	// mediaformat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mediaformat.UpdateDefaultUpdatedAt = mediaformatDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediaformatDescName is the schema descriptor for name field.
	mediaformatDescName := mediaformatFields[0].Descriptor()
	// mediaformat.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mediaformat.NameValidator = mediaformatDescName.Validators[0].(func(string) error)
	// mediaformatDescURL is the schema descriptor for url field.
	mediaformatDescURL := mediaformatFields[2].Descriptor()
	// mediaformat.URLValidator is a validator for the "url" field. It is called by the builders before save.
	mediaformat.URLValidator = mediaformatDescURL.Validators[0].(func(string) error)
	// mediaformatDescID is the schema descriptor for id field.
	mediaformatDescID := mediaformatMixinFields0[0].Descriptor()
	// mediaformat.DefaultID holds the default value on creation for the id field.
	mediaformat.DefaultID = mediaformatDescID.Default.(func() uuid.UUID)
}
