// Code generated by ent, DO NOT EDIT.

package mediaformat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldTenantID, v))
}

// CreatedByID applies equality check predicate on the "created_by_id" field. It's identical to CreatedByIDEQ.
func CreatedByID(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedByID applies equality check predicate on the "updated_by_id" field. It's identical to UpdatedByIDEQ.
func UpdatedByID(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedByID applies equality check predicate on the "deleted_by_id" field. It's identical to DeletedByIDEQ.
func DeletedByID(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldDeletedAt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldPublishedAt, v))
}

// ArchivedAt applies equality check predicate on the "archived_at" field. It's identical to ArchivedAtEQ.
func ArchivedAt(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldArchivedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldName, v))
}

// Ext applies equality check predicate on the "ext" field. It's identical to ExtEQ.
func Ext(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldExt, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldURL, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldHash, v))
}

// Mime applies equality check predicate on the "mime" field. It's identical to MimeEQ.
func Mime(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldMime, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldSize, v))
}

// SizeInBytes applies equality check predicate on the "size_in_bytes" field. It's identical to SizeInBytesEQ.
func SizeInBytes(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldSizeInBytes, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldHeight, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldPath, v))
}

// IsURLSigned applies equality check predicate on the "is_url_signed" field. It's identical to IsURLSignedEQ.
func IsURLSigned(v bool) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldIsURLSigned, v))
}

// MediaID applies equality check predicate on the "media_id" field. It's identical to MediaIDEQ.
func MediaID(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldMediaID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldTenantID, v))
}

// CreatedByIDEQ applies the EQ predicate on the "created_by_id" field.
func CreatedByIDEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedByIDNEQ applies the NEQ predicate on the "created_by_id" field.
func CreatedByIDNEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldCreatedByID, v))
}

// CreatedByIDIn applies the In predicate on the "created_by_id" field.
func CreatedByIDIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldCreatedByID, vs...))
}

// CreatedByIDNotIn applies the NotIn predicate on the "created_by_id" field.
func CreatedByIDNotIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldCreatedByID, vs...))
}

// CreatedByIDGT applies the GT predicate on the "created_by_id" field.
func CreatedByIDGT(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldCreatedByID, v))
}

// CreatedByIDGTE applies the GTE predicate on the "created_by_id" field.
func CreatedByIDGTE(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldCreatedByID, v))
}

// CreatedByIDLT applies the LT predicate on the "created_by_id" field.
func CreatedByIDLT(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldCreatedByID, v))
}

// CreatedByIDLTE applies the LTE predicate on the "created_by_id" field.
func CreatedByIDLTE(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldCreatedByID, v))
}

// CreatedByIDIsNil applies the IsNil predicate on the "created_by_id" field.
func CreatedByIDIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldCreatedByID))
}

// CreatedByIDNotNil applies the NotNil predicate on the "created_by_id" field.
func CreatedByIDNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldCreatedByID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedByIDEQ applies the EQ predicate on the "updated_by_id" field.
func UpdatedByIDEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedByIDNEQ applies the NEQ predicate on the "updated_by_id" field.
func UpdatedByIDNEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldUpdatedByID, v))
}

// UpdatedByIDIn applies the In predicate on the "updated_by_id" field.
func UpdatedByIDIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDNotIn applies the NotIn predicate on the "updated_by_id" field.
func UpdatedByIDNotIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDGT applies the GT predicate on the "updated_by_id" field.
func UpdatedByIDGT(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldUpdatedByID, v))
}

// UpdatedByIDGTE applies the GTE predicate on the "updated_by_id" field.
func UpdatedByIDGTE(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldUpdatedByID, v))
}

// UpdatedByIDLT applies the LT predicate on the "updated_by_id" field.
func UpdatedByIDLT(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldUpdatedByID, v))
}

// UpdatedByIDLTE applies the LTE predicate on the "updated_by_id" field.
func UpdatedByIDLTE(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldUpdatedByID, v))
}

// UpdatedByIDIsNil applies the IsNil predicate on the "updated_by_id" field.
func UpdatedByIDIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldUpdatedByID))
}

// UpdatedByIDNotNil applies the NotNil predicate on the "updated_by_id" field.
func UpdatedByIDNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldUpdatedByID))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedByIDEQ applies the EQ predicate on the "deleted_by_id" field.
func DeletedByIDEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedByIDNEQ applies the NEQ predicate on the "deleted_by_id" field.
func DeletedByIDNEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldDeletedByID, v))
}

// DeletedByIDIn applies the In predicate on the "deleted_by_id" field.
func DeletedByIDIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldDeletedByID, vs...))
}

// DeletedByIDNotIn applies the NotIn predicate on the "deleted_by_id" field.
func DeletedByIDNotIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldDeletedByID, vs...))
}

// DeletedByIDGT applies the GT predicate on the "deleted_by_id" field.
func DeletedByIDGT(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldDeletedByID, v))
}

// DeletedByIDGTE applies the GTE predicate on the "deleted_by_id" field.
func DeletedByIDGTE(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldDeletedByID, v))
}

// DeletedByIDLT applies the LT predicate on the "deleted_by_id" field.
func DeletedByIDLT(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldDeletedByID, v))
}

// DeletedByIDLTE applies the LTE predicate on the "deleted_by_id" field.
func DeletedByIDLTE(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldDeletedByID, v))
}

// DeletedByIDIsNil applies the IsNil predicate on the "deleted_by_id" field.
func DeletedByIDIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldDeletedByID))
}

// DeletedByIDNotNil applies the NotNil predicate on the "deleted_by_id" field.
func DeletedByIDNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldDeletedByID))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldDeletedAt))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldPublishedAt))
}

// ArchivedAtEQ applies the EQ predicate on the "archived_at" field.
func ArchivedAtEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldArchivedAt, v))
}

// ArchivedAtNEQ applies the NEQ predicate on the "archived_at" field.
func ArchivedAtNEQ(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldArchivedAt, v))
}

// ArchivedAtIn applies the In predicate on the "archived_at" field.
func ArchivedAtIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldArchivedAt, vs...))
}

// ArchivedAtNotIn applies the NotIn predicate on the "archived_at" field.
func ArchivedAtNotIn(vs ...time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldArchivedAt, vs...))
}

// ArchivedAtGT applies the GT predicate on the "archived_at" field.
func ArchivedAtGT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldArchivedAt, v))
}

// ArchivedAtGTE applies the GTE predicate on the "archived_at" field.
func ArchivedAtGTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldArchivedAt, v))
}

// ArchivedAtLT applies the LT predicate on the "archived_at" field.
func ArchivedAtLT(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldArchivedAt, v))
}

// ArchivedAtLTE applies the LTE predicate on the "archived_at" field.
func ArchivedAtLTE(v time.Time) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldArchivedAt, v))
}

// ArchivedAtIsNil applies the IsNil predicate on the "archived_at" field.
func ArchivedAtIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldArchivedAt))
}

// ArchivedAtNotNil applies the NotNil predicate on the "archived_at" field.
func ArchivedAtNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldArchivedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldName, v))
}

// ExtEQ applies the EQ predicate on the "ext" field.
func ExtEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldExt, v))
}

// ExtNEQ applies the NEQ predicate on the "ext" field.
func ExtNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldExt, v))
}

// ExtIn applies the In predicate on the "ext" field.
func ExtIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldExt, vs...))
}

// ExtNotIn applies the NotIn predicate on the "ext" field.
func ExtNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldExt, vs...))
}

// ExtGT applies the GT predicate on the "ext" field.
func ExtGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldExt, v))
}

// ExtGTE applies the GTE predicate on the "ext" field.
func ExtGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldExt, v))
}

// ExtLT applies the LT predicate on the "ext" field.
func ExtLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldExt, v))
}

// ExtLTE applies the LTE predicate on the "ext" field.
func ExtLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldExt, v))
}

// ExtContains applies the Contains predicate on the "ext" field.
func ExtContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldExt, v))
}

// ExtHasPrefix applies the HasPrefix predicate on the "ext" field.
func ExtHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldExt, v))
}

// ExtHasSuffix applies the HasSuffix predicate on the "ext" field.
func ExtHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldExt, v))
}

// ExtIsNil applies the IsNil predicate on the "ext" field.
func ExtIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldExt))
}

// ExtNotNil applies the NotNil predicate on the "ext" field.
func ExtNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldExt))
}

// ExtEqualFold applies the EqualFold predicate on the "ext" field.
func ExtEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldExt, v))
}

// ExtContainsFold applies the ContainsFold predicate on the "ext" field.
func ExtContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldExt, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldURL, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldHash, v))
}

// HashIsNil applies the IsNil predicate on the "hash" field.
func HashIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldHash))
}

// HashNotNil applies the NotNil predicate on the "hash" field.
func HashNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldHash))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldHash, v))
}

// MimeEQ applies the EQ predicate on the "mime" field.
func MimeEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldMime, v))
}

// MimeNEQ applies the NEQ predicate on the "mime" field.
func MimeNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldMime, v))
}

// MimeIn applies the In predicate on the "mime" field.
func MimeIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldMime, vs...))
}

// MimeNotIn applies the NotIn predicate on the "mime" field.
func MimeNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldMime, vs...))
}

// MimeGT applies the GT predicate on the "mime" field.
func MimeGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldMime, v))
}

// MimeGTE applies the GTE predicate on the "mime" field.
func MimeGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldMime, v))
}

// MimeLT applies the LT predicate on the "mime" field.
func MimeLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldMime, v))
}

// MimeLTE applies the LTE predicate on the "mime" field.
func MimeLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldMime, v))
}

// MimeContains applies the Contains predicate on the "mime" field.
func MimeContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldMime, v))
}

// MimeHasPrefix applies the HasPrefix predicate on the "mime" field.
func MimeHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldMime, v))
}

// MimeHasSuffix applies the HasSuffix predicate on the "mime" field.
func MimeHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldMime, v))
}

// MimeIsNil applies the IsNil predicate on the "mime" field.
func MimeIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldMime))
}

// MimeNotNil applies the NotNil predicate on the "mime" field.
func MimeNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldMime))
}

// MimeEqualFold applies the EqualFold predicate on the "mime" field.
func MimeEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldMime, v))
}

// MimeContainsFold applies the ContainsFold predicate on the "mime" field.
func MimeContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldMime, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v float64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldSize))
}

// SizeInBytesEQ applies the EQ predicate on the "size_in_bytes" field.
func SizeInBytesEQ(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldSizeInBytes, v))
}

// SizeInBytesNEQ applies the NEQ predicate on the "size_in_bytes" field.
func SizeInBytesNEQ(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldSizeInBytes, v))
}

// SizeInBytesIn applies the In predicate on the "size_in_bytes" field.
func SizeInBytesIn(vs ...int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldSizeInBytes, vs...))
}

// SizeInBytesNotIn applies the NotIn predicate on the "size_in_bytes" field.
func SizeInBytesNotIn(vs ...int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldSizeInBytes, vs...))
}

// SizeInBytesGT applies the GT predicate on the "size_in_bytes" field.
func SizeInBytesGT(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldSizeInBytes, v))
}

// SizeInBytesGTE applies the GTE predicate on the "size_in_bytes" field.
func SizeInBytesGTE(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldSizeInBytes, v))
}

// SizeInBytesLT applies the LT predicate on the "size_in_bytes" field.
func SizeInBytesLT(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldSizeInBytes, v))
}

// SizeInBytesLTE applies the LTE predicate on the "size_in_bytes" field.
func SizeInBytesLTE(v int64) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldSizeInBytes, v))
}

// SizeInBytesIsNil applies the IsNil predicate on the "size_in_bytes" field.
func SizeInBytesIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldSizeInBytes))
}

// SizeInBytesNotNil applies the NotNil predicate on the "size_in_bytes" field.
func SizeInBytesNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldSizeInBytes))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldHeight))
}

// ProviderMetadataIsNil applies the IsNil predicate on the "provider_metadata" field.
func ProviderMetadataIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldProviderMetadata))
}

// ProviderMetadataNotNil applies the NotNil predicate on the "provider_metadata" field.
func ProviderMetadataNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldProviderMetadata))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldContainsFold(FieldPath, v))
}

// IsURLSignedEQ applies the EQ predicate on the "is_url_signed" field.
func IsURLSignedEQ(v bool) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldIsURLSigned, v))
}

// IsURLSignedNEQ applies the NEQ predicate on the "is_url_signed" field.
func IsURLSignedNEQ(v bool) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldIsURLSigned, v))
}

// IsURLSignedIsNil applies the IsNil predicate on the "is_url_signed" field.
func IsURLSignedIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldIsURLSigned))
}

// IsURLSignedNotNil applies the NotNil predicate on the "is_url_signed" field.
func IsURLSignedNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldIsURLSigned))
}

// MediaIDEQ applies the EQ predicate on the "media_id" field.
func MediaIDEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldEQ(FieldMediaID, v))
}

// MediaIDNEQ applies the NEQ predicate on the "media_id" field.
func MediaIDNEQ(v uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNEQ(FieldMediaID, v))
}

// MediaIDIn applies the In predicate on the "media_id" field.
func MediaIDIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIn(FieldMediaID, vs...))
}

// MediaIDNotIn applies the NotIn predicate on the "media_id" field.
func MediaIDNotIn(vs ...uuid.UUID) predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotIn(FieldMediaID, vs...))
}

// MediaIDIsNil applies the IsNil predicate on the "media_id" field.
func MediaIDIsNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldIsNull(FieldMediaID))
}

// MediaIDNotNil applies the NotNil predicate on the "media_id" field.
func MediaIDNotNil() predicate.MediaFormat {
	return predicate.MediaFormat(sql.FieldNotNull(FieldMediaID))
}

// HasMedia applies the HasEdge predicate on the "media" edge.
func HasMedia() predicate.MediaFormat {
	return predicate.MediaFormat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MediaTable, MediaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMediaWith applies the HasEdge predicate on the "media" edge with a given conditions (other predicates).
func HasMediaWith(preds ...predicate.Media) predicate.MediaFormat {
	return predicate.MediaFormat(func(s *sql.Selector) {
		step := newMediaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaFormat) predicate.MediaFormat {
	return predicate.MediaFormat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaFormat) predicate.MediaFormat {
	return predicate.MediaFormat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaFormat) predicate.MediaFormat {
	return predicate.MediaFormat(sql.NotPredicates(p))
}
