// Code generated by ent, DO NOT EDIT.

package media

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the media type in the database.
	Label = "media"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreatedByID holds the string denoting the created_by_id field in the database.
	FieldCreatedByID = "created_by_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedByID holds the string denoting the updated_by_id field in the database.
	FieldUpdatedByID = "updated_by_id"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedByID holds the string denoting the deleted_by_id field in the database.
	FieldDeletedByID = "deleted_by_id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldArchivedAt holds the string denoting the archived_at field in the database.
	FieldArchivedAt = "archived_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAlternativeText holds the string denoting the alternative_text field in the database.
	FieldAlternativeText = "alternative_text"
	// FieldCaption holds the string denoting the caption field in the database.
	FieldCaption = "caption"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldExt holds the string denoting the ext field in the database.
	FieldExt = "ext"
	// FieldMime holds the string denoting the mime field in the database.
	FieldMime = "mime"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPreviewURL holds the string denoting the preview_url field in the database.
	FieldPreviewURL = "preview_url"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderMetadata holds the string denoting the provider_metadata field in the database.
	FieldProviderMetadata = "provider_metadata"
	// FieldFolderPath holds the string denoting the folder_path field in the database.
	FieldFolderPath = "folder_path"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldIsURLSigned holds the string denoting the is_url_signed field in the database.
	FieldIsURLSigned = "is_url_signed"
	// EdgeFormats holds the string denoting the formats edge name in mutations.
	EdgeFormats = "formats"
	// Table holds the table name of the media in the database.
	Table = "media"
	// FormatsTable is the table that holds the formats relation/edge.
	FormatsTable = "media_formats"
	// FormatsInverseTable is the table name for the MediaFormat entity.
	// It exists in this package in order to avoid circular dependency with the "mediaformat" package.
	FormatsInverseTable = "media_formats"
	// FormatsColumn is the table column denoting the formats relation/edge.
	FormatsColumn = "media_id"
)

// Columns holds all SQL columns for media fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCreatedByID,
	FieldCreatedAt,
	FieldUpdatedByID,
	FieldUpdatedAt,
	FieldDeletedByID,
	FieldDeletedAt,
	FieldPublishedAt,
	FieldArchivedAt,
	FieldName,
	FieldAlternativeText,
	FieldCaption,
	FieldWidth,
	FieldHeight,
	FieldHash,
	FieldExt,
	FieldMime,
	FieldSize,
	FieldURL,
	FieldPreviewURL,
	FieldProvider,
	FieldProviderMetadata,
	FieldFolderPath,
	FieldLocale,
	FieldIsURLSigned,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Media queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCreatedByID orders the results by the created_by_id field.
func ByCreatedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedByID orders the results by the updated_by_id field.
func ByUpdatedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByID, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedByID orders the results by the deleted_by_id field.
func ByDeletedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedByID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByArchivedAt orders the results by the archived_at field.
func ByArchivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchivedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAlternativeText orders the results by the alternative_text field.
func ByAlternativeText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlternativeText, opts...).ToFunc()
}

// ByCaption orders the results by the caption field.
func ByCaption(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaption, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByExt orders the results by the ext field.
func ByExt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExt, opts...).ToFunc()
}

// ByMime orders the results by the mime field.
func ByMime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMime, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByPreviewURL orders the results by the preview_url field.
func ByPreviewURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviewURL, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByFolderPath orders the results by the folder_path field.
func ByFolderPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderPath, opts...).ToFunc()
}

// ByLocale orders the results by the locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}

// ByIsURLSigned orders the results by the is_url_signed field.
func ByIsURLSigned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsURLSigned, opts...).ToFunc()
}

// ByFormatsCount orders the results by formats count.
func ByFormatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFormatsStep(), opts...)
	}
}

// ByFormats orders the results by formats terms.
func ByFormats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFormatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFormatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FormatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FormatsTable, FormatsColumn),
	)
}
