// Code generated by ent, DO NOT EDIT.

package media

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/leeforge/framework/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldTenantID, v))
}

// CreatedByID applies equality check predicate on the "created_by_id" field. It's identical to CreatedByIDEQ.
func CreatedByID(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedByID applies equality check predicate on the "updated_by_id" field. It's identical to UpdatedByIDEQ.
func UpdatedByID(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedByID applies equality check predicate on the "deleted_by_id" field. It's identical to DeletedByIDEQ.
func DeletedByID(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldDeletedAt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldPublishedAt, v))
}

// ArchivedAt applies equality check predicate on the "archived_at" field. It's identical to ArchivedAtEQ.
func ArchivedAt(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldArchivedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldName, v))
}

// AlternativeText applies equality check predicate on the "alternative_text" field. It's identical to AlternativeTextEQ.
func AlternativeText(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldAlternativeText, v))
}

// Caption applies equality check predicate on the "caption" field. It's identical to CaptionEQ.
func Caption(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldCaption, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldHeight, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldHash, v))
}

// Ext applies equality check predicate on the "ext" field. It's identical to ExtEQ.
func Ext(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldExt, v))
}

// Mime applies equality check predicate on the "mime" field. It's identical to MimeEQ.
func Mime(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldMime, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v float64) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldSize, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldURL, v))
}

// PreviewURL applies equality check predicate on the "preview_url" field. It's identical to PreviewURLEQ.
func PreviewURL(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldPreviewURL, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldProvider, v))
}

// FolderPath applies equality check predicate on the "folder_path" field. It's identical to FolderPathEQ.
func FolderPath(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldFolderPath, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldLocale, v))
}

// IsURLSigned applies equality check predicate on the "is_url_signed" field. It's identical to IsURLSignedEQ.
func IsURLSigned(v bool) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldIsURLSigned, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldTenantID, v))
}

// CreatedByIDEQ applies the EQ predicate on the "created_by_id" field.
func CreatedByIDEQ(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedByIDNEQ applies the NEQ predicate on the "created_by_id" field.
func CreatedByIDNEQ(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldCreatedByID, v))
}

// CreatedByIDIn applies the In predicate on the "created_by_id" field.
func CreatedByIDIn(vs ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldCreatedByID, vs...))
}

// CreatedByIDNotIn applies the NotIn predicate on the "created_by_id" field.
func CreatedByIDNotIn(vs ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldCreatedByID, vs...))
}

// CreatedByIDGT applies the GT predicate on the "created_by_id" field.
func CreatedByIDGT(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldCreatedByID, v))
}

// CreatedByIDGTE applies the GTE predicate on the "created_by_id" field.
func CreatedByIDGTE(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldCreatedByID, v))
}

// CreatedByIDLT applies the LT predicate on the "created_by_id" field.
func CreatedByIDLT(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldCreatedByID, v))
}

// CreatedByIDLTE applies the LTE predicate on the "created_by_id" field.
func CreatedByIDLTE(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldCreatedByID, v))
}

// CreatedByIDIsNil applies the IsNil predicate on the "created_by_id" field.
func CreatedByIDIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldCreatedByID))
}

// CreatedByIDNotNil applies the NotNil predicate on the "created_by_id" field.
func CreatedByIDNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldCreatedByID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedByIDEQ applies the EQ predicate on the "updated_by_id" field.
func UpdatedByIDEQ(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedByIDNEQ applies the NEQ predicate on the "updated_by_id" field.
func UpdatedByIDNEQ(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldUpdatedByID, v))
}

// UpdatedByIDIn applies the In predicate on the "updated_by_id" field.
func UpdatedByIDIn(vs ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDNotIn applies the NotIn predicate on the "updated_by_id" field.
func UpdatedByIDNotIn(vs ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDGT applies the GT predicate on the "updated_by_id" field.
func UpdatedByIDGT(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldUpdatedByID, v))
}

// UpdatedByIDGTE applies the GTE predicate on the "updated_by_id" field.
func UpdatedByIDGTE(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldUpdatedByID, v))
}

// UpdatedByIDLT applies the LT predicate on the "updated_by_id" field.
func UpdatedByIDLT(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldUpdatedByID, v))
}

// UpdatedByIDLTE applies the LTE predicate on the "updated_by_id" field.
func UpdatedByIDLTE(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldUpdatedByID, v))
}

// UpdatedByIDIsNil applies the IsNil predicate on the "updated_by_id" field.
func UpdatedByIDIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldUpdatedByID))
}

// UpdatedByIDNotNil applies the NotNil predicate on the "updated_by_id" field.
func UpdatedByIDNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldUpdatedByID))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedByIDEQ applies the EQ predicate on the "deleted_by_id" field.
func DeletedByIDEQ(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedByIDNEQ applies the NEQ predicate on the "deleted_by_id" field.
func DeletedByIDNEQ(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldDeletedByID, v))
}

// DeletedByIDIn applies the In predicate on the "deleted_by_id" field.
func DeletedByIDIn(vs ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldDeletedByID, vs...))
}

// DeletedByIDNotIn applies the NotIn predicate on the "deleted_by_id" field.
func DeletedByIDNotIn(vs ...uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldDeletedByID, vs...))
}

// DeletedByIDGT applies the GT predicate on the "deleted_by_id" field.
func DeletedByIDGT(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldDeletedByID, v))
}

// DeletedByIDGTE applies the GTE predicate on the "deleted_by_id" field.
func DeletedByIDGTE(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldDeletedByID, v))
}

// DeletedByIDLT applies the LT predicate on the "deleted_by_id" field.
func DeletedByIDLT(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldDeletedByID, v))
}

// DeletedByIDLTE applies the LTE predicate on the "deleted_by_id" field.
func DeletedByIDLTE(v uuid.UUID) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldDeletedByID, v))
}

// DeletedByIDIsNil applies the IsNil predicate on the "deleted_by_id" field.
func DeletedByIDIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldDeletedByID))
}

// DeletedByIDNotNil applies the NotNil predicate on the "deleted_by_id" field.
func DeletedByIDNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldDeletedByID))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldDeletedAt))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldPublishedAt))
}

// ArchivedAtEQ applies the EQ predicate on the "archived_at" field.
func ArchivedAtEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldArchivedAt, v))
}

// ArchivedAtNEQ applies the NEQ predicate on the "archived_at" field.
func ArchivedAtNEQ(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldArchivedAt, v))
}

// ArchivedAtIn applies the In predicate on the "archived_at" field.
func ArchivedAtIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldArchivedAt, vs...))
}

// ArchivedAtNotIn applies the NotIn predicate on the "archived_at" field.
func ArchivedAtNotIn(vs ...time.Time) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldArchivedAt, vs...))
}

// ArchivedAtGT applies the GT predicate on the "archived_at" field.
func ArchivedAtGT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldArchivedAt, v))
}

// ArchivedAtGTE applies the GTE predicate on the "archived_at" field.
func ArchivedAtGTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldArchivedAt, v))
}

// ArchivedAtLT applies the LT predicate on the "archived_at" field.
func ArchivedAtLT(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldArchivedAt, v))
}

// ArchivedAtLTE applies the LTE predicate on the "archived_at" field.
func ArchivedAtLTE(v time.Time) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldArchivedAt, v))
}

// ArchivedAtIsNil applies the IsNil predicate on the "archived_at" field.
func ArchivedAtIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldArchivedAt))
}

// ArchivedAtNotNil applies the NotNil predicate on the "archived_at" field.
func ArchivedAtNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldArchivedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldName, v))
}

// AlternativeTextEQ applies the EQ predicate on the "alternative_text" field.
func AlternativeTextEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldAlternativeText, v))
}

// AlternativeTextNEQ applies the NEQ predicate on the "alternative_text" field.
func AlternativeTextNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldAlternativeText, v))
}

// AlternativeTextIn applies the In predicate on the "alternative_text" field.
func AlternativeTextIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldAlternativeText, vs...))
}

// AlternativeTextNotIn applies the NotIn predicate on the "alternative_text" field.
func AlternativeTextNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldAlternativeText, vs...))
}

// AlternativeTextGT applies the GT predicate on the "alternative_text" field.
func AlternativeTextGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldAlternativeText, v))
}

// AlternativeTextGTE applies the GTE predicate on the "alternative_text" field.
func AlternativeTextGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldAlternativeText, v))
}

// AlternativeTextLT applies the LT predicate on the "alternative_text" field.
func AlternativeTextLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldAlternativeText, v))
}

// AlternativeTextLTE applies the LTE predicate on the "alternative_text" field.
func AlternativeTextLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldAlternativeText, v))
}

// AlternativeTextContains applies the Contains predicate on the "alternative_text" field.
func AlternativeTextContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldAlternativeText, v))
}

// AlternativeTextHasPrefix applies the HasPrefix predicate on the "alternative_text" field.
func AlternativeTextHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldAlternativeText, v))
}

// AlternativeTextHasSuffix applies the HasSuffix predicate on the "alternative_text" field.
func AlternativeTextHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldAlternativeText, v))
}

// AlternativeTextIsNil applies the IsNil predicate on the "alternative_text" field.
func AlternativeTextIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldAlternativeText))
}

// AlternativeTextNotNil applies the NotNil predicate on the "alternative_text" field.
func AlternativeTextNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldAlternativeText))
}

// AlternativeTextEqualFold applies the EqualFold predicate on the "alternative_text" field.
func AlternativeTextEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldAlternativeText, v))
}

// AlternativeTextContainsFold applies the ContainsFold predicate on the "alternative_text" field.
func AlternativeTextContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldAlternativeText, v))
}

// CaptionEQ applies the EQ predicate on the "caption" field.
func CaptionEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldCaption, v))
}

// CaptionNEQ applies the NEQ predicate on the "caption" field.
func CaptionNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldCaption, v))
}

// CaptionIn applies the In predicate on the "caption" field.
func CaptionIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldCaption, vs...))
}

// CaptionNotIn applies the NotIn predicate on the "caption" field.
func CaptionNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldCaption, vs...))
}

// CaptionGT applies the GT predicate on the "caption" field.
func CaptionGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldCaption, v))
}

// CaptionGTE applies the GTE predicate on the "caption" field.
func CaptionGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldCaption, v))
}

// CaptionLT applies the LT predicate on the "caption" field.
func CaptionLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldCaption, v))
}

// CaptionLTE applies the LTE predicate on the "caption" field.
func CaptionLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldCaption, v))
}

// CaptionContains applies the Contains predicate on the "caption" field.
func CaptionContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldCaption, v))
}

// CaptionHasPrefix applies the HasPrefix predicate on the "caption" field.
func CaptionHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldCaption, v))
}

// CaptionHasSuffix applies the HasSuffix predicate on the "caption" field.
func CaptionHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldCaption, v))
}

// CaptionIsNil applies the IsNil predicate on the "caption" field.
func CaptionIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldCaption))
}

// CaptionNotNil applies the NotNil predicate on the "caption" field.
func CaptionNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldCaption))
}

// CaptionEqualFold applies the EqualFold predicate on the "caption" field.
func CaptionEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldCaption, v))
}

// CaptionContainsFold applies the ContainsFold predicate on the "caption" field.
func CaptionContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldCaption, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldHeight))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldHash, v))
}

// HashIsNil applies the IsNil predicate on the "hash" field.
func HashIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldHash))
}

// HashNotNil applies the NotNil predicate on the "hash" field.
func HashNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldHash))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldHash, v))
}

// ExtEQ applies the EQ predicate on the "ext" field.
func ExtEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldExt, v))
}

// ExtNEQ applies the NEQ predicate on the "ext" field.
func ExtNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldExt, v))
}

// ExtIn applies the In predicate on the "ext" field.
func ExtIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldExt, vs...))
}

// ExtNotIn applies the NotIn predicate on the "ext" field.
func ExtNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldExt, vs...))
}

// ExtGT applies the GT predicate on the "ext" field.
func ExtGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldExt, v))
}

// ExtGTE applies the GTE predicate on the "ext" field.
func ExtGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldExt, v))
}

// ExtLT applies the LT predicate on the "ext" field.
func ExtLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldExt, v))
}

// ExtLTE applies the LTE predicate on the "ext" field.
func ExtLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldExt, v))
}

// ExtContains applies the Contains predicate on the "ext" field.
func ExtContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldExt, v))
}

// ExtHasPrefix applies the HasPrefix predicate on the "ext" field.
func ExtHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldExt, v))
}

// ExtHasSuffix applies the HasSuffix predicate on the "ext" field.
func ExtHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldExt, v))
}

// ExtIsNil applies the IsNil predicate on the "ext" field.
func ExtIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldExt))
}

// ExtNotNil applies the NotNil predicate on the "ext" field.
func ExtNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldExt))
}

// ExtEqualFold applies the EqualFold predicate on the "ext" field.
func ExtEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldExt, v))
}

// ExtContainsFold applies the ContainsFold predicate on the "ext" field.
func ExtContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldExt, v))
}

// MimeEQ applies the EQ predicate on the "mime" field.
func MimeEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldMime, v))
}

// MimeNEQ applies the NEQ predicate on the "mime" field.
func MimeNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldMime, v))
}

// MimeIn applies the In predicate on the "mime" field.
func MimeIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldMime, vs...))
}

// MimeNotIn applies the NotIn predicate on the "mime" field.
func MimeNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldMime, vs...))
}

// MimeGT applies the GT predicate on the "mime" field.
func MimeGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldMime, v))
}

// MimeGTE applies the GTE predicate on the "mime" field.
func MimeGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldMime, v))
}

// MimeLT applies the LT predicate on the "mime" field.
func MimeLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldMime, v))
}

// MimeLTE applies the LTE predicate on the "mime" field.
func MimeLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldMime, v))
}

// MimeContains applies the Contains predicate on the "mime" field.
func MimeContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldMime, v))
}

// MimeHasPrefix applies the HasPrefix predicate on the "mime" field.
func MimeHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldMime, v))
}

// MimeHasSuffix applies the HasSuffix predicate on the "mime" field.
func MimeHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldMime, v))
}

// MimeIsNil applies the IsNil predicate on the "mime" field.
func MimeIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldMime))
}

// MimeNotNil applies the NotNil predicate on the "mime" field.
func MimeNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldMime))
}

// MimeEqualFold applies the EqualFold predicate on the "mime" field.
func MimeEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldMime, v))
}

// MimeContainsFold applies the ContainsFold predicate on the "mime" field.
func MimeContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldMime, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v float64) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v float64) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...float64) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...float64) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v float64) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v float64) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v float64) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v float64) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldSize))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldURL, v))
}

// PreviewURLEQ applies the EQ predicate on the "preview_url" field.
func PreviewURLEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldPreviewURL, v))
}

// PreviewURLNEQ applies the NEQ predicate on the "preview_url" field.
func PreviewURLNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldPreviewURL, v))
}

// PreviewURLIn applies the In predicate on the "preview_url" field.
func PreviewURLIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldPreviewURL, vs...))
}

// PreviewURLNotIn applies the NotIn predicate on the "preview_url" field.
func PreviewURLNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldPreviewURL, vs...))
}

// PreviewURLGT applies the GT predicate on the "preview_url" field.
func PreviewURLGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldPreviewURL, v))
}

// PreviewURLGTE applies the GTE predicate on the "preview_url" field.
func PreviewURLGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldPreviewURL, v))
}

// PreviewURLLT applies the LT predicate on the "preview_url" field.
func PreviewURLLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldPreviewURL, v))
}

// PreviewURLLTE applies the LTE predicate on the "preview_url" field.
func PreviewURLLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldPreviewURL, v))
}

// PreviewURLContains applies the Contains predicate on the "preview_url" field.
func PreviewURLContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldPreviewURL, v))
}

// PreviewURLHasPrefix applies the HasPrefix predicate on the "preview_url" field.
func PreviewURLHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldPreviewURL, v))
}

// PreviewURLHasSuffix applies the HasSuffix predicate on the "preview_url" field.
func PreviewURLHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldPreviewURL, v))
}

// PreviewURLIsNil applies the IsNil predicate on the "preview_url" field.
func PreviewURLIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldPreviewURL))
}

// PreviewURLNotNil applies the NotNil predicate on the "preview_url" field.
func PreviewURLNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldPreviewURL))
}

// PreviewURLEqualFold applies the EqualFold predicate on the "preview_url" field.
func PreviewURLEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldPreviewURL, v))
}

// PreviewURLContainsFold applies the ContainsFold predicate on the "preview_url" field.
func PreviewURLContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldPreviewURL, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderMetadataIsNil applies the IsNil predicate on the "provider_metadata" field.
func ProviderMetadataIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldProviderMetadata))
}

// ProviderMetadataNotNil applies the NotNil predicate on the "provider_metadata" field.
func ProviderMetadataNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldProviderMetadata))
}

// FolderPathEQ applies the EQ predicate on the "folder_path" field.
func FolderPathEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldFolderPath, v))
}

// FolderPathNEQ applies the NEQ predicate on the "folder_path" field.
func FolderPathNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldFolderPath, v))
}

// FolderPathIn applies the In predicate on the "folder_path" field.
func FolderPathIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldFolderPath, vs...))
}

// FolderPathNotIn applies the NotIn predicate on the "folder_path" field.
func FolderPathNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldFolderPath, vs...))
}

// FolderPathGT applies the GT predicate on the "folder_path" field.
func FolderPathGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldFolderPath, v))
}

// FolderPathGTE applies the GTE predicate on the "folder_path" field.
func FolderPathGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldFolderPath, v))
}

// FolderPathLT applies the LT predicate on the "folder_path" field.
func FolderPathLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldFolderPath, v))
}

// FolderPathLTE applies the LTE predicate on the "folder_path" field.
func FolderPathLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldFolderPath, v))
}

// FolderPathContains applies the Contains predicate on the "folder_path" field.
func FolderPathContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldFolderPath, v))
}

// FolderPathHasPrefix applies the HasPrefix predicate on the "folder_path" field.
func FolderPathHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldFolderPath, v))
}

// FolderPathHasSuffix applies the HasSuffix predicate on the "folder_path" field.
func FolderPathHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldFolderPath, v))
}

// FolderPathIsNil applies the IsNil predicate on the "folder_path" field.
func FolderPathIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldFolderPath))
}

// FolderPathNotNil applies the NotNil predicate on the "folder_path" field.
func FolderPathNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldFolderPath))
}

// FolderPathEqualFold applies the EqualFold predicate on the "folder_path" field.
func FolderPathEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldFolderPath, v))
}

// FolderPathContainsFold applies the ContainsFold predicate on the "folder_path" field.
func FolderPathContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldFolderPath, v))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.Media {
	return predicate.Media(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.Media {
	return predicate.Media(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.Media {
	return predicate.Media(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.Media {
	return predicate.Media(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.Media {
	return predicate.Media(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.Media {
	return predicate.Media(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.Media {
	return predicate.Media(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleIsNil applies the IsNil predicate on the "locale" field.
func LocaleIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldLocale))
}

// LocaleNotNil applies the NotNil predicate on the "locale" field.
func LocaleNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldLocale))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.Media {
	return predicate.Media(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.Media {
	return predicate.Media(sql.FieldContainsFold(FieldLocale, v))
}

// IsURLSignedEQ applies the EQ predicate on the "is_url_signed" field.
func IsURLSignedEQ(v bool) predicate.Media {
	return predicate.Media(sql.FieldEQ(FieldIsURLSigned, v))
}

// IsURLSignedNEQ applies the NEQ predicate on the "is_url_signed" field.
func IsURLSignedNEQ(v bool) predicate.Media {
	return predicate.Media(sql.FieldNEQ(FieldIsURLSigned, v))
}

// IsURLSignedIsNil applies the IsNil predicate on the "is_url_signed" field.
func IsURLSignedIsNil() predicate.Media {
	return predicate.Media(sql.FieldIsNull(FieldIsURLSigned))
}

// IsURLSignedNotNil applies the NotNil predicate on the "is_url_signed" field.
func IsURLSignedNotNil() predicate.Media {
	return predicate.Media(sql.FieldNotNull(FieldIsURLSigned))
}

// HasFormats applies the HasEdge predicate on the "formats" edge.
func HasFormats() predicate.Media {
	return predicate.Media(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FormatsTable, FormatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFormatsWith applies the HasEdge predicate on the "formats" edge with a given conditions (other predicates).
func HasFormatsWith(preds ...predicate.MediaFormat) predicate.Media {
	return predicate.Media(func(s *sql.Selector) {
		step := newFormatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Media) predicate.Media {
	return predicate.Media(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Media) predicate.Media {
	return predicate.Media(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Media) predicate.Media {
	return predicate.Media(sql.NotPredicates(p))
}
