// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CasbinPolicy is the predicate function for casbinpolicy builders.
type CasbinPolicy func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// MediaFormat is the predicate function for mediaformat builders.
type MediaFormat func(*sql.Selector)
